### 연습문제. 중복데이터 처리

In [2]:
# 필요 모듈
import numpy as np
import pandas as pd

print(f'numpy : {np.__version__}, pandas : {pd.__version__}')

numpy : 2.5.2, pandas : 3.0.5

In [3]:
# 여러 변수 출력 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

다음의 데이터에 대하여 주어진 문제를 해결하기 위한 코드를 작성하시오.

In [5]:
df = pd.DataFrame({
    "user_id":   [101, 102, 103, 101, 104, 105, 105, 106, 107, 107],
    "email":     ["kim@a.com", "lee@a.com", "park@a.com", "KIM@A.COM ", None,
                  "choi@a.com", "choi@a.com", "han@a.com", "yoon@a.com", "yoon@a.com"],
    "phone":     ["010-1111-2222", "010-3333-4444", "010-5555-6666", "01011112222", "010-7777-8888",
                  "010-9999-0000", "010-9999-0000", "010-2222-3333", "010-4444-5555", "010-4444-5555"],
    "score":     [90, 85, 88, 92, 70, 60, 75, 95, 81, 81],
    "updated_at":[
        "2026-02-01", "2026-02-03", "2026-02-05", "2026-02-10", "2026-02-11",
        "2026-02-02", "2026-02-12", "2026-02-15", "2026-02-01", "2026-02-20"
    ]
})

df["updated_at"] = pd.to_datetime(df["updated_at"])
df

   user_id       email          phone  score updated_at
0      101   kim@a.com  010-1111-2222     90 2026-02-01
1      102   lee@a.com  010-3333-4444     85 2026-02-03
2      103  park@a.com  010-5555-6666     88 2026-02-05
3      101  KIM@A.COM     01011112222     92 2026-02-10
4      104         NaN  010-7777-8888     70 2026-02-11
5      105  choi@a.com  010-9999-0000     60 2026-02-02
6      105  choi@a.com  010-9999-0000     75 2026-02-12
7      106   han@a.com  010-2222-3333     95 2026-02-15
8      107  yoon@a.com  010-4444-5555     81 2026-02-01
9      107  yoon@a.com  010-4444-5555     81 2026-02-20

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     10 non-null     int64
 1   email       9 non-null      str
 2   phone       10 non-null     str
 3   score       10 non-null     int64
 4   updated_at  10 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 532.0 bytes

1. `user_id` 기준으로 중복된 행만 조회하기

In [10]:
df[df.duplicated(subset=['user_id'], keep=False)]

   user_id       email          phone  score updated_at
0      101   kim@a.com  010-1111-2222     90 2026-02-01
3      101  KIM@A.COM     01011112222     92 2026-02-10
5      105  choi@a.com  010-9999-0000     60 2026-02-02
6      105  choi@a.com  010-9999-0000     75 2026-02-12
8      107  yoon@a.com  010-4444-5555     81 2026-02-01
9      107  yoon@a.com  010-4444-5555     81 2026-02-20

2. `email`  기준으로 중복된 데이터 그룹 전체 조회하기(첫번째 행도 포함)

In [20]:
df[  df['email'].str.lower().str.strip().duplicated(keep=False)  ]

   user_id       email          phone  score updated_at
0      101   kim@a.com  010-1111-2222     90 2026-02-01
3      101  KIM@A.COM     01011112222     92 2026-02-10
5      105  choi@a.com  010-9999-0000     60 2026-02-02
6      105  choi@a.com  010-9999-0000     75 2026-02-12
8      107  yoon@a.com  010-4444-5555     81 2026-02-01
9      107  yoon@a.com  010-4444-5555     81 2026-02-20

3. `user_id` 기준으로 중복을 제거하고, 첫번째 데이터만 남기기

In [23]:
df.drop_duplicates(subset=['user_id'], keep='first')

   user_id       email          phone  score updated_at
0      101   kim@a.com  010-1111-2222     90 2026-02-01
1      102   lee@a.com  010-3333-4444     85 2026-02-03
2      103  park@a.com  010-5555-6666     88 2026-02-05
4      104         NaN  010-7777-8888     70 2026-02-11
5      105  choi@a.com  010-9999-0000     60 2026-02-02
7      106   han@a.com  010-2222-3333     95 2026-02-15
8      107  yoon@a.com  010-4444-5555     81 2026-02-01

4. `user_id` 기준으로 중복을 제거하고 가장 마지막 데이터만 남기기

In [24]:
df.drop_duplicates(subset=['user_id'], keep='last')

   user_id       email          phone  score updated_at
1      102   lee@a.com  010-3333-4444     85 2026-02-03
2      103  park@a.com  010-5555-6666     88 2026-02-05
3      101  KIM@A.COM     01011112222     92 2026-02-10
4      104         NaN  010-7777-8888     70 2026-02-11
6      105  choi@a.com  010-9999-0000     75 2026-02-12
7      106   han@a.com  010-2222-3333     95 2026-02-15
9      107  yoon@a.com  010-4444-5555     81 2026-02-20

5. `email`  기준으로 중복된 데이터는 전부 제거하고 유니크(unique)한 데이터만 남기기

In [29]:
df2 = df.copy()
df2['email'] = df2['email'].str.lower().str.strip()
df2.drop_duplicates(subset=['email'], keep=False)

   user_id       email          phone  score updated_at
1      102   lee@a.com  010-3333-4444     85 2026-02-03
2      103  park@a.com  010-5555-6666     88 2026-02-05
4      104         NaN  010-7777-8888     70 2026-02-11
7      106   han@a.com  010-2222-3333     95 2026-02-15

6. `user_id` 기준으로 최신(updates_at) 데이터만 남기기

In [37]:
df.sort_values(by='updated_at')

   user_id       email          phone  score updated_at
0      101   kim@a.com  010-1111-2222     90 2026-02-01
8      107  yoon@a.com  010-4444-5555     81 2026-02-01
5      105  choi@a.com  010-9999-0000     60 2026-02-02
1      102   lee@a.com  010-3333-4444     85 2026-02-03
2      103  park@a.com  010-5555-6666     88 2026-02-05
3      101  KIM@A.COM     01011112222     92 2026-02-10
4      104         NaN  010-7777-8888     70 2026-02-11
6      105  choi@a.com  010-9999-0000     75 2026-02-12
7      106   han@a.com  010-2222-3333     95 2026-02-15
9      107  yoon@a.com  010-4444-5555     81 2026-02-20

In [36]:
df.sort_values(by='updated_at').drop_duplicates(subset=['user_id'], keep ='last')

   user_id       email          phone  score updated_at
1      102   lee@a.com  010-3333-4444     85 2026-02-03
2      103  park@a.com  010-5555-6666     88 2026-02-05
3      101  KIM@A.COM     01011112222     92 2026-02-10
4      104         NaN  010-7777-8888     70 2026-02-11
6      105  choi@a.com  010-9999-0000     75 2026-02-12
7      106   han@a.com  010-2222-3333     95 2026-02-15
9      107  yoon@a.com  010-4444-5555     81 2026-02-20

7. `email` 컬럼의 중복 여부를 표시하는 새로운 컬럼 `id_dup_email` 생성하기

In [43]:
is_unique = df['email'].str.lower().str.strip().duplicated( keep=False )

df['id_dup_email'] = is_unique

8. `phone 컬럼에서 숫자만 남기고  `phone_num` 컬럼 생성한 후 이 컬럼 기준으로 중복데이터 조회하기

In [45]:
df

   user_id       email          phone  score updated_at  id_dup_email
0      101   kim@a.com  010-1111-2222     90 2026-02-01          True
1      102   lee@a.com  010-3333-4444     85 2026-02-03         False
2      103  park@a.com  010-5555-6666     88 2026-02-05         False
3      101  KIM@A.COM     01011112222     92 2026-02-10          True
4      104         NaN  010-7777-8888     70 2026-02-11         False
5      105  choi@a.com  010-9999-0000     60 2026-02-02          True
6      105  choi@a.com  010-9999-0000     75 2026-02-12          True
7      106   han@a.com  010-2222-3333     95 2026-02-15         False
8      107  yoon@a.com  010-4444-5555     81 2026-02-01          True
9      107  yoon@a.com  010-4444-5555     81 2026-02-20          True

In [48]:
df['phone_num'] = df['phone'].str.replace('-','').str.strip()

In [50]:
df[ df.duplicated(subset=['phone_num'], keep=False) ]

,user_id,email,phone,score,updated_at,id_dup_email,phone_num
0,101,kim@a.com,010-1111-2222,90,2026-02-01,True,01011112222
3,101,KIM@A.COM,01011112222,92,2026-02-10,True,01011112222
5,105,choi@a.com,010-9999-0000,60,2026-02-02,True,01099990000
6,105,choi@a.com,010-9999-0000,75,2026-02-12,True,01099990000
8,107,yoon@a.com,010-4444-5555,81,2026-02-01,True,01044445555
9,107,yoon@a.com,010-4444-5555,81,2026-02-20,True,01044445555

9. `user_id`별로 score가 가장 높은 데이터만 남기기

In [54]:
df.sort_values(by='score')

,user_id,email,phone,score,updated_at,id_dup_email,phone_num
5,105,choi@a.com,010-9999-0000,60,2026-02-02,True,01099990000
4,104,NaN,010-7777-8888,70,2026-02-11,False,01077778888
6,105,choi@a.com,010-9999-0000,75,2026-02-12,True,01099990000
8,107,yoon@a.com,010-4444-5555,81,2026-02-01,True,01044445555
9,107,yoon@a.com,010-4444-5555,81,2026-02-20,True,01044445555
1,102,lee@a.com,010-3333-4444,85,2026-02-03,False,01033334444
2,103,park@a.com,010-5555-6666,88,2026-02-05,False,01055556666
0,101,kim@a.com,010-1111-2222,90,2026-02-01,True,01011112222
3,101,KIM@A.COM,01011112222,92,2026-02-10,True,01011112222
7,106,han@a.com,010-2222-3333,95,2026-02-15,False,01022223333

In [63]:
df.sort_values(by='score').drop_duplicates(subset=['user_id'], keep='last')
df[~df.sort_values(by='score').duplicated(subset=['user_id'], keep='last')]
df.sort_values(by='score').duplicated(subset=['user_id'], keep='last')

,user_id,email,phone,score,updated_at,id_dup_email,phone_num
4,104,NaN,010-7777-8888,70,2026-02-11,False,01077778888
6,105,choi@a.com,010-9999-0000,75,2026-02-12,True,01099990000
9,107,yoon@a.com,010-4444-5555,81,2026-02-20,True,01044445555
1,102,lee@a.com,010-3333-4444,85,2026-02-03,False,01033334444
2,103,park@a.com,010-5555-6666,88,2026-02-05,False,01055556666
3,101,KIM@A.COM,01011112222,92,2026-02-10,True,01011112222
7,106,han@a.com,010-2222-3333,95,2026-02-15,False,01022223333

C:\Users\acorn2\AppData\Local\Temp\ipykernel_24672\2572502402.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[~df.sort_values(by='score').duplicated(subset=['user_id'], keep='last')]

,user_id,email,phone,score,updated_at,id_dup_email,phone_num
1,102,lee@a.com,010-3333-4444,85,2026-02-03,False,01033334444
2,103,park@a.com,010-5555-6666,88,2026-02-05,False,01055556666
3,101,KIM@A.COM,01011112222,92,2026-02-10,True,01011112222
4,104,NaN,010-7777-8888,70,2026-02-11,False,01077778888
6,105,choi@a.com,010-9999-0000,75,2026-02-12,True,01099990000
7,106,han@a.com,010-2222-3333,95,2026-02-15,False,01022223333
9,107,yoon@a.com,010-4444-5555,81,2026-02-20,True,01044445555

5     True
4    False
6    False
8     True
9    False
1    False
2    False
0     True
3    False
7    False
dtype: bool

10. `email` 데이터를 정규화(공백 제거 + 소문자 변환)하여 email_norm 컬럼을 생성하기

---