# BeautifulSoup 종합실습
## 온라인 서점 도서 정보 수집하기


> 아래 문제의 빈 코드 셀을 직접 작성하면서 실습하세요.

### 실습 환경 준비

In [1]:
from bs4 import BeautifulSoup

### 실습용 HTML
: 온라인 서점의 상품 목록을 단순화한 예제

In [2]:
html = '''
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>AI 온라인 서점</title>
</head>
<body>
<div id="container">
    <h1>AI 온라인 서점</h1>

    <div class="book-list">

        <div class="book" data-category="python">
            <h2 class="title"><a href="/book/101">혼자 공부하는 파이썬</a></h2>
            <p class="author">홍길동</p>
            <p class="publisher">한빛출판사</p>
            <span class="price">22,000원</span>
            <span class="rating">4.8</span>
        </div>

        <div class="book" data-category="database">
            <h2 class="title"><a href="/book/102">MySQL 데이터베이스</a></h2>
            <p class="author">이순신</p>
            <p class="publisher">정보출판사</p>
            <span class="price">28,000원</span>
            <span class="rating">4.5</span>
        </div>

        <div class="book" data-category="python">
            <h2 class="title"><a href="/book/103">파이썬 데이터 분석</a></h2>
            <p class="author">김유신</p>
            <p class="publisher">한빛출판사</p>
            <span class="price">30,000원</span>
            <span class="rating">4.9</span>
        </div>

        <div class="book" data-category="ai">
            <h2 class="title"><a href="/book/104">머신러닝 입문</a></h2>
            <p class="author">강감찬</p>
            <p class="publisher">AI북스</p>
            <span class="price">35,000원</span>
            <span class="rating">4.7</span>
        </div>

        <div class="book" data-category="ai">
            <h2 class="title"><a href="/book/105">딥러닝과 생성형 AI</a></h2>
            <p class="author">장영실</p>
            <p class="publisher">AI북스</p>
            <span class="price">42,000원</span>
            <span class="rating">4.9</span>
        </div>

    </div>
</div>
</body>
</html>
'''

soup = BeautifulSoup(html, "html.parser")
print("실습용 HTML 로드 완료")

실습용 HTML 로드 완료

#### 문제 1. 페이지 제목 추출

`select_one()`을 사용하여 `<h1>`의 텍스트를 출력하세요.

**실행 결과**

```text
AI 온라인 서점
```

In [3]:
text = soup.select_one('h1')
print(text.text)

AI 온라인 서점

#### 문제 2. 모든 도서 영역 선택

`select()`를 사용하여 class가 `book`인 모든 요소를 선택하고 도서 수를 출력하세요.

**실행 결과**

```text
등록 도서 수 : 5
```

In [4]:
book = soup.select('.book')
print(f'등록 도서 수 : {len(book)}')

등록 도서 수 : 5

#### 문제 3. 모든 도서 제목 출력

각 `.book` 요소를 반복하면서 도서 제목을 추출하세요.

**실행 결과**

```text
혼자 공부하는 파이썬
MySQL 데이터베이스
파이썬 데이터 분석
머신러닝 입문
딥러닝과 생성형 AI
```

In [5]:
book_title = soup.select('.book h2.title')

for t in book_title:
    print(t.text)

혼자 공부하는 파이썬
MySQL 데이터베이스
파이썬 데이터 분석
머신러닝 입문
딥러닝과 생성형 AI

#### 문제 4. 도서 상세정보 추출

각 도서에서 다음 정보를 추출하되 불필요한 공백을 제거하세요.

- 제목
- 저자
- 출판사
- 가격
- 평점

In [6]:
book_title = soup.select('.book h2.title')
title = [ t.text for t in book_title ]
book_author = soup.select('.book p.author')
author = [ a.text for a in book_author ]
book_publisher = soup.select('.book p.publisher')
publisher = [ p.text for p in book_publisher ]
book_price = soup.select('.book span.price')
price = [ p.text for p in book_price ]
book_rating = soup.select('.book span.rating')
rating = [ r.text for r in book_rating ]

book = {
    '제목' : title,
    '저자' : author,
    '출판사' : publisher,
    '가격' : price,
    '평점' : rating
}
book

{'제목': ['혼자 공부하는 파이썬', 'MySQL 데이터베이스', '파이썬 데이터 분석', '머신러닝 입문', '딥러닝과 생성형 AI'],
 '저자': ['홍길동', '이순신', '김유신', '강감찬', '장영실'],
 '출판사': ['한빛출판사', '정보출판사', '한빛출판사', 'AI북스', 'AI북스'],
 '가격': ['22,000원', '28,000원', '30,000원', '35,000원', '42,000원'],
 '평점': ['4.8', '4.5', '4.9', '4.7', '4.9']}

#### 문제 5. 상세페이지 링크 추출

CSS Selector를 이용하여 제목과 `href` 속성값을 출력하세요.

**실행 결과 예**

```text
혼자 공부하는 파이썬 : /book/101
MySQL 데이터베이스 : /book/102
...
```

In [7]:
book_title = soup.select('.book h2.title')
title = [ t.text for t in book_title ]

book_href = soup.select('.book h2 a')
href = [ h['href'] for h in book_href ]

for t, h in zip(title, href):
    print(f'{t} : {h}')


        # <div class="book" data-category="ai">
        #     <h2 class="title"><a href="/book/105">딥러닝과 생성형 AI</a></h2>
        #     <p class="author">장영실</p>
        #     <p class="publisher">AI북스</p>
        #     <span class="price">42,000원</span>
        #     <span class="rating">4.9</span>

혼자 공부하는 파이썬 : /book/101
MySQL 데이터베이스 : /book/102
파이썬 데이터 분석 : /book/103
머신러닝 입문 : /book/104
딥러닝과 생성형 AI : /book/105

#### 문제 6. 속성 Selector 사용

`data-category="python"`인 도서만 CSS 속성 Selector로 선택하여 제목을 출력하세요.

**실행 결과**

```text
혼자 공부하는 파이썬
파이썬 데이터 분석
```

In [8]:
book_title = soup.select('.book[data-category="python"] h2.title')
for t in book_title:
    print(t.text)

혼자 공부하는 파이썬
파이썬 데이터 분석

#### 문제 7. 특정 출판사의 도서 검색

모든 도서를 반복하면서 출판사가 `AI북스`인 도서의 제목만 출력하세요.

**실행 결과**

```text
머신러닝 입문
딥러닝과 생성형 AI
```

In [9]:
book = soup.select('.book')

for b in book:
    if b.select_one('.publisher').text == 'AI북스':
        print(b.select_one('.title').text)



        # <div class="book" data-category="ai">
        #     <h2 class="title"><a href="/book/105">딥러닝과 생성형 AI</a></h2>
        #     <p class="author">장영실</p>
        #     <p class="publisher">AI북스</p>
        #     <span class="price">42,000원</span>
        #     <span class="rating">4.9</span>

머신러닝 입문
딥러닝과 생성형 AI

#### 문제 8. 가격 데이터 정제 및 조건 검색

가격은 현재 `"22,000원"`과 같은 문자열입니다.

1. `,`와 `원`을 제거합니다.
2. `int()`를 이용하여 정수로 변환합니다.
3. 가격이 **30,000원 이상인 도서**만 출력합니다.

**실행 결과**

```text
파이썬 데이터 분석 : 30000원
머신러닝 입문 : 35000원
딥러닝과 생성형 AI : 42000원
```

In [10]:
book = soup.select('.book')
for b in book:
    book_title = b.select_one('.book h2.title').text
    price_to_num = b.select_one('.price').text[:-1].replace(",","")
    price = int(price_to_num)
    # print(f'{book_title} : {price}원')
    if price >= 30000:
        print(f'{book_title} : {price}원')
        
    

        # <div class="book" data-category="ai">
        #     <h2 class="title"><a href="/book/105">딥러닝과 생성형 AI</a></h2>
        #     <p class="author">장영실</p>
        #     <p class="publisher">AI북스</p>
        #     <span class="price">42,000원</span>
        #     <span class="rating">4.9</span>

파이썬 데이터 분석 : 30000원
머신러닝 입문 : 35000원
딥러닝과 생성형 AI : 42000원

#### 문제 9. 평점 조건 검색

평점을 `float`형으로 변환하고 **4.8 이상인 도서**만 출력하세요.

**실행 결과**

```text
혼자 공부하는 파이썬 : 4.8
파이썬 데이터 분석 : 4.9
딥러닝과 생성형 AI : 4.9
```

In [11]:
book = soup.select('.book')
for b in book:
    book_title = b.select_one('.book h2.title').text
    book_rating = float(b.select_one('.rating').text)
    
    if book_rating >= 4.8:
        print(f'{book_title} : {book_rating}')
        
        # <div class="book" data-category="ai">
        #     <h2 class="title"><a href="/book/105">딥러닝과 생성형 AI</a></h2>
        #     <p class="author">장영실</p>
        #     <p class="publisher">AI북스</p>
        #     <span class="price">42,000원</span>
        #     <span class="rating">4.9</span>

혼자 공부하는 파이썬 : 4.8
파이썬 데이터 분석 : 4.9
딥러닝과 생성형 AI : 4.9

#### 문제 10. 크롤링 데이터를 리스트와 딕셔너리로 저장

각 도서의 정보를 다음 구조로 `book_list`에 저장하세요.

```python
[
    {
        "title": "혼자 공부하는 파이썬",
        "author": "홍길동",
        "publisher": "한빛출판사",
        "category": "python",
        "price": 22000,
        "rating": 4.8,
        "link": "/book/101"
    },
    ...
]
```

가격은 `int`, 평점은 `float`로 저장합니다.

In [12]:
book_list = []
for b in soup.select('.book'):
    title = b.select_one('.book h2.title').text
    
    author = b.select_one('.book p.author').text
    publisher = b.select_one('.book p.publisher').text
    catagory = b['data-category']
    
    book_price = b.select_one('.book span.price')
    price = int(book_price.text[:-1].replace(",",""))
    rating = float(b.select_one('.book span.rating').text)
    link = b.select_one('a')['href']
    
    book_info = {
        'title' : title,
        'author' : author,
        'publisher' : publisher,
        "category": catagory,
        'price' : price,
        'rating' : rating,
        "link": link
    }
    book_list.append(book_info)


book_list
        # <div class="book" data-category="ai">
        #     <h2 class="title"><a href="/book/105">딥러닝과 생성형 AI</a></h2>
        #     <p class="author">장영실</p>
        #     <p class="publisher">AI북스</p>
        #     <span class="price">42,000원</span>
        #     <span class="rating">4.9</span>

[{'title': '혼자 공부하는 파이썬',
  'author': '홍길동',
  'publisher': '한빛출판사',
  'category': 'python',
  'price': 22000,
  'rating': 4.8,
  'link': '/book/101'},
 {'title': 'MySQL 데이터베이스',
  'author': '이순신',
  'publisher': '정보출판사',
  'category': 'database',
  'price': 28000,
  'rating': 4.5,
  'link': '/book/102'},
 {'title': '파이썬 데이터 분석',
  'author': '김유신',
  'publisher': '한빛출판사',
  'category': 'python',
  'price': 30000,
  'rating': 4.9,
  'link': '/book/103'},
 {'title': '머신러닝 입문',
  'author': '강감찬',
  'publisher': 'AI북스',
  'category': 'ai',
  'price': 35000,
  'rating': 4.7,
  'link': '/book/104'},
 {'title': '딥러닝과 생성형 AI',
  'author': '장영실',
  'publisher': 'AI북스',
  'category': 'ai',
  'price': 42000,
  'rating': 4.9,
  'link': '/book/105'}]

#### 문제 11. 수집 데이터 분석

앞에서 생성한 `book_list`를 이용하여 다음 항목을 구하세요.

1. 전체 도서 수
2. 전체 도서의 평균 가격
3. 가장 비싼 도서
4. 최고 평점
5. 최고 평점을 받은 모든 도서
6. 카테고리별 도서 수

**기대 결과 일부**

```text
전체 도서 수 : 5권
평균 가격 : 31,400원
가장 비싼 도서 : 딥러닝과 생성형 AI / 42,000원
최고 평점 : 4.9
```

In [21]:
book_num = len(book_list)

book_price = []
# book_price = [ b['price'] for b in book_list ]

for b in book_list:
    book_price.append(b['price'])

book_price_avg = sum(book_price)/len(book_price)

most_exp_book = sorted(book_list, key = lambda x:x['price'])[-1]
highest_rate = max(book_list, key = lambda x:x['rating'])['rating']

print(f'전체 도서 수 : {book_num}')
print(f'평균 가격 : {book_price_avg}')
print(f'가장 비싼 도서 : {most_exp_book['title']} / {most_exp_book['price']}')
print(f'최고 평점 : {highest_rate}')

전체 도서 수 : 5
평균 가격 : 31400.0
가장 비싼 도서 : 딥러닝과 생성형 AI / 42000
최고 평점 : 4.9

### 최종 종합문제

지금까지 작성한 코드를 하나의 프로그램(.py)으로 통합하세요.

#### 처리 과정

```text
HTML
 ↓
BeautifulSoup
 ↓
select(".book")
 ↓
각 도서 반복
 ↓
select_one()
 ↓
제목 / 저자 / 출판사 / 카테고리 / 가격 / 평점 / 링크
 ↓
데이터 정제
 ↓
dict 생성
 ↓
list 저장
 ↓
조건 검색 및 분석
```

### 최종 프로그램 요구사항

- 전체 도서 목록을 번호와 함께 출력
- 가격은 천 단위 쉼표를 포함하여 출력
- 전체 도서 수 출력
- 평균 가격 출력
- 최고 가격 도서 출력
- 최고 평점과 해당 도서 출력
- `python`, `database`, `ai` 카테고리별 도서 수 출력

In [23]:
# HTML
html = '''
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>AI 온라인 서점</title>
</head>
<body>
<div id="container">
    <h1>AI 온라인 서점</h1>

    <div class="book-list">

        <div class="book" data-category="python">
            <h2 class="title"><a href="/book/101">혼자 공부하는 파이썬</a></h2>
            <p class="author">홍길동</p>
            <p class="publisher">한빛출판사</p>
            <span class="price">22,000원</span>
            <span class="rating">4.8</span>
        </div>

        <div class="book" data-category="database">
            <h2 class="title"><a href="/book/102">MySQL 데이터베이스</a></h2>
            <p class="author">이순신</p>
            <p class="publisher">정보출판사</p>
            <span class="price">28,000원</span>
            <span class="rating">4.5</span>
        </div>

        <div class="book" data-category="python">
            <h2 class="title"><a href="/book/103">파이썬 데이터 분석</a></h2>
            <p class="author">김유신</p>
            <p class="publisher">한빛출판사</p>
            <span class="price">30,000원</span>
            <span class="rating">4.9</span>
        </div>

        <div class="book" data-category="ai">
            <h2 class="title"><a href="/book/104">머신러닝 입문</a></h2>
            <p class="author">강감찬</p>
            <p class="publisher">AI북스</p>
            <span class="price">35,000원</span>
            <span class="rating">4.7</span>
        </div>

        <div class="book" data-category="ai">
            <h2 class="title"><a href="/book/105">딥러닝과 생성형 AI</a></h2>
            <p class="author">장영실</p>
            <p class="publisher">AI북스</p>
            <span class="price">42,000원</span>
            <span class="rating">4.9</span>
        </div>

    </div>
</div>
</body>
</html>
'''

soup = BeautifulSoup(html, "html.parser")
print("실습용 HTML 로드 완료")

실습용 HTML 로드 완료

In [25]:
# list 저장
book_list = []
for b in soup.select('.book'):
    title = b.select_one('.book h2.title').text
    
    author = b.select_one('.book p.author').text
    publisher = b.select_one('.book p.publisher').text
    catagory = b['data-category']
    
    book_price = b.select_one('.book span.price')
    price = int(book_price.text[:-1].replace(",",""))
    rating = float(b.select_one('.book span.rating').text)
    link = b.select_one('a')['href']
    
    book_info = {
        'title' : title,
        'author' : author,
        'publisher' : publisher,
        "category": catagory,
        'price' : price,
        'rating' : rating,
        "link": link
    }
    book_list.append(book_info)

In [29]:
# 데이터 프레임 저장
import pandas as pd
book_df = pd.DataFrame(book_list)
book_df

          title author publisher  category  price  rating       link
0   혼자 공부하는 파이썬    홍길동     한빛출판사    python  22000     4.8  /book/101
1  MySQL 데이터베이스    이순신     정보출판사  database  28000     4.5  /book/102
2    파이썬 데이터 분석    김유신     한빛출판사    python  30000     4.9  /book/103
3       머신러닝 입문    강감찬      AI북스        ai  35000     4.7  /book/104
4   딥러닝과 생성형 AI    장영실      AI북스        ai  42000     4.9  /book/105

In [31]:
#전체 도서 목록을 번호와 함께 출력
book_df

          title author publisher  category  price  rating       link
0   혼자 공부하는 파이썬    홍길동     한빛출판사    python  22000     4.8  /book/101
1  MySQL 데이터베이스    이순신     정보출판사  database  28000     4.5  /book/102
2    파이썬 데이터 분석    김유신     한빛출판사    python  30000     4.9  /book/103
3       머신러닝 입문    강감찬      AI북스        ai  35000     4.7  /book/104
4   딥러닝과 생성형 AI    장영실      AI북스        ai  42000     4.9  /book/105

In [33]:
#가격은 천 단위 쉼표를 포함하여 출력
book_df['price'] = book_df['price'].apply(lambda p: f"{p:,}원")
book_df

          title author publisher  category    price  rating       link
0   혼자 공부하는 파이썬    홍길동     한빛출판사    python  22,000원     4.8  /book/101
1  MySQL 데이터베이스    이순신     정보출판사  database  28,000원     4.5  /book/102
2    파이썬 데이터 분석    김유신     한빛출판사    python  30,000원     4.9  /book/103
3       머신러닝 입문    강감찬      AI북스        ai  35,000원     4.7  /book/104
4   딥러닝과 생성형 AI    장영실      AI북스        ai  42,000원     4.9  /book/105

In [35]:
#전체 도서 수 출력
len(book_list)

5

In [37]:
# 평균 가격 출력
sum( [ b['price'] for b in book_list ] ) / len(book_list)

31400.0

In [49]:
#최고 가격 도서 출력
# def key1(x):
#     return x['price']
# exp_book = sorted(book_list, key = key1)[-1]
# #exp_book = sorted(book_list, key = lambda x: x['price'])[-1]
# exp_book
exp_price = max( b['price'] for b in book_list)
exp_book = [ b for b in book_list if b['price'] == exp_price ]
exp_book = pd.DataFrame(exp_book)

book_df[ book_df['price'] == max( book_df['price'])]

         title author publisher category    price  rating       link
4  딥러닝과 생성형 AI    장영실      AI북스       ai  42,000원     4.9  /book/105

In [50]:
#최고 평점과 해당 도서 출력
highest_rating = max( b['rating'] for b in book_list)
highest_book = [ b for b in book_list if b['rating'] == highest_rating ]
highest_book = pd.DataFrame(highest_book)


book_df[ book_df['rating'] == max( book_df['rating'])]

         title author publisher category    price  rating       link
2   파이썬 데이터 분석    김유신     한빛출판사   python  30,000원     4.9  /book/103
4  딥러닝과 생성형 AI    장영실      AI북스       ai  42,000원     4.9  /book/105

In [52]:
# `python`, `database`, `ai` 카테고리별 도서 수 출력
cat = 'python'
print( len( [ b for b in book_list if b['category'] == cat ] ) )

cat = 'database'
print( len( [ b for b in book_list if b['category'] == cat ] ) )

cat = 'ai'
print( len( [ b for b in book_list if b['category'] == cat ] ) )

2
1
2

## 도전 문제

기본 문제를 완료했다면 다음 기능을 추가해 보세요.

1. 사용자에게 최소 가격을 입력받아 해당 가격 이상의 도서 검색
2. 사용자에게 카테고리를 입력받아 해당 카테고리의 도서 검색
3. 도서를 가격이 높은 순으로 정렬
4. 도서를 평점이 높은 순으로 정렬
5. `book_list`를 Pandas `DataFrame`으로 변환
6. 결과를 CSV 파일로 저장

```python
import pandas as pd

df = pd.DataFrame(book_list)
```

In [61]:
# 사용자에게 최소 가격을 입력받아 해당 가격 이상의 도서 검색
low_price = int(input("최소가격을 입력하시오"))

search_book = [ b for b in book_list if b['price'] >= low_price ]
search_book = pd.DataFrame(search_book)
search_book

#book_df[ book_df['price'] >= low_price ]

최소가격을 입력하시오 30000

         title author publisher category  price  rating       link
0   파이썬 데이터 분석    김유신     한빛출판사   python  30000     4.9  /book/103
1      머신러닝 입문    강감찬      AI북스       ai  35000     4.7  /book/104
2  딥러닝과 생성형 AI    장영실      AI북스       ai  42000     4.9  /book/105

In [64]:
# 사용자에게 카테고리를 입력받아 해당 카테고리의 도서 검색
cat = input("어떤 카테고리의 도서를 확인하시겠습니까? : ")

search_book = [ b for b in book_list if b['category'] == cat ]
search_book = pd.DataFrame(search_book)
search_book

# book_df[ book_df['category'] == cat ]

어떤 카테고리의 도서를 확인하시겠습니까? :  ai

         title author publisher category    price  rating       link
3      머신러닝 입문    강감찬      AI북스       ai  35,000원     4.7  /book/104
4  딥러닝과 생성형 AI    장영실      AI북스       ai  42,000원     4.9  /book/105

In [69]:
# 도서를 가격이 높은 순으로 정렬
book_sorted_price_reverse = sorted(book_list, key = lambda x: x['price'], reverse = True)
book_sorted_price_reverse

#book_df.sort_values(by='price', ascending=False)

[{'title': '딥러닝과 생성형 AI',
  'author': '장영실',
  'publisher': 'AI북스',
  'category': 'ai',
  'price': 42000,
  'rating': 4.9,
  'link': '/book/105'},
 {'title': '머신러닝 입문',
  'author': '강감찬',
  'publisher': 'AI북스',
  'category': 'ai',
  'price': 35000,
  'rating': 4.7,
  'link': '/book/104'},
 {'title': '파이썬 데이터 분석',
  'author': '김유신',
  'publisher': '한빛출판사',
  'category': 'python',
  'price': 30000,
  'rating': 4.9,
  'link': '/book/103'},
 {'title': 'MySQL 데이터베이스',
  'author': '이순신',
  'publisher': '정보출판사',
  'category': 'database',
  'price': 28000,
  'rating': 4.5,
  'link': '/book/102'},
 {'title': '혼자 공부하는 파이썬',
  'author': '홍길동',
  'publisher': '한빛출판사',
  'category': 'python',
  'price': 22000,
  'rating': 4.8,
  'link': '/book/101'}]

In [72]:
# 도서를 평점이 높은 순으로 정렬
book_sorted_rating_reverse = sorted(book_list, key = lambda x: x['rating'], reverse = True)
book_sorted_rating_reverse

#book_df.sort_values(by='rating', ascending=False)

          title author publisher  category    price  rating       link
4   딥러닝과 생성형 AI    장영실      AI북스        ai  42,000원     4.9  /book/105
3       머신러닝 입문    강감찬      AI북스        ai  35,000원     4.7  /book/104
2    파이썬 데이터 분석    김유신     한빛출판사    python  30,000원     4.9  /book/103
1  MySQL 데이터베이스    이순신     정보출판사  database  28,000원     4.5  /book/102
0   혼자 공부하는 파이썬    홍길동     한빛출판사    python  22,000원     4.8  /book/101

In [65]:
# book_list를 Pandas DataFrame으로 변환
book_df

          title author publisher  category    price  rating       link
0   혼자 공부하는 파이썬    홍길동     한빛출판사    python  22,000원     4.8  /book/101
1  MySQL 데이터베이스    이순신     정보출판사  database  28,000원     4.5  /book/102
2    파이썬 데이터 분석    김유신     한빛출판사    python  30,000원     4.9  /book/103
3       머신러닝 입문    강감찬      AI북스        ai  35,000원     4.7  /book/104
4   딥러닝과 생성형 AI    장영실      AI북스        ai  42,000원     4.9  /book/105

In [73]:
# 결과를 CSV 파일로 저장
book_df.to_csv('books.csv', index = False, encoding='utf-8-sig')