## 파이썬과 MySQL 연동 #1

### 1. 파이썬에서 MySQL 연동을 위한 pymysql 라이브러리 설치

- https://github.com/PyMySQL/PyMySQL
- https://pymysql.readthedocs.io/en/latest/
- https://peps.python.org/pep-0249/

In [ ]:
# pymysql 설치
# !pip install mysql

In [ ]:
# mysql workbench에서 crawlDB 스키마 생성 후 crawluser 계정 생성
# drop database if exists crawlDB;
# create schema crawlDB default character set utf8mb4;

### 2 MySQL workbench에서 DB 생성

In [ ]:
# mysql workbench에서 crawlDB 스키마 생성 후 crawluser 계정 생성
drop database if exists crawlDB;
create schema crawlDB default character set utf8mb4;

# 사용자 계정 등록
create user 'crawluser'@'%' identified by 'acorn1234';

# 권한 부여
grant all privileges on crawldb.* to 'crawluser'@'%';

# 권한 부여하는 기준 
-- 개발환경 : all privileges(모든 권한)
-- 운영 : select, delete, insert, update
-- 배포/관리 : create, alter, drop 별도 계정


# 권한 반영 
flush privileges;

# 권한 확인
show grants for 'crawluser'@'%';

### 3. 파이썬에서 MySQL 데이터 생성

#### 1) pymysql 라이브러리 임포트

In [1]:
import pymysql
pymysql.__version__

'2.2.8'

#### 2) MySQL 연결

- **pymysql.connect(host=서버IP주소, user=사용자, password=암호, df=데이터베이스, charset=문자세트)**
- 연결자 = pymysql.connect(연결옵션)
- 연결자는 파이썬에서 MySQL의 DB를 연결해 줌
- 연결이 성공해도 메시지가 나오지 않음
- https://pymysql.readthedocs.io/en/latest/modules/connections.html

In [3]:
conn = pymysql.connect(host='127.0.0.1',
                       user = 'crawluser',
                       password = 'acorn1234',
                       db = 'crawlDB',
                       charset='utf8')

#### 3) cursor 생성

- cursor이름 = 연결자.**cursor()**
- cursor는 데이터베이스에 SQL문을 실행하거나 실행된 결과를 돌려받는 통로
- https://pymysql.readthedocs.io/en/latest/modules/cursors.html

In [5]:
cur = conn.cursor()

#### 4) 테이블 생성

- SQL 문을 커서이름.execute() 함수의 매개변수로 넘겨주면 SQL문이 데이터베이스에서 실행됨
- cursor이름.**execute**(SQL문)
- 실행결과는 0 또는 다른 번호가 나옴

In [6]:
sql1 = 'drop table if exists customer;'
sql2 = '''
    create table customer(
        id int not null primary key,
        name varchar(20) not null,
        tel char(13),
        birth date
    );
'''

In [8]:
cur.execute(sql1)
cur.execute(sql2)

0

#### 5) 테이블 데이터 삽입(insert)

- cursor이름.execute(삽입SQL문)
- 실행결과의 번호는 삽입한 데이터 수가 됨

In [9]:
sql3 = '''
    insert into customer (id, name, tel, birth)
        values  (1,'김바람','010-123-1111','2000-01-01'),
                (2,'남구름','010-222-1111','2010-01-01'),
                (3,'서바다','010-321-2111','2001-05-01'),
                (4,'홍하늘','010-123-1311','2010-02-01')
                ;
'''
cur.execute(sql3)

4

#### 6) 데이터베이스 변경사항 저장 : commit()

- **연결자.commit()**
- 데이터베이스에 삽입한 데이터를 확실하게 저장 : 변경 내용 확정

In [10]:
# cursor 가 아닌 연결자로 해야함
conn.commit()


**데이터 삽입과 commit()**
- execute() : SQL문 한 번 실행
- executemany() : 동일SQL문 여러 데이터에 실행

|구분|execute()|executemany()|
|---|:---:|:---:|
|목적|SQL 1회 실행|동일 SQL 반복 실행|
|전달데이터|튜플 1개|튜플들의 리스트|
|SELECT|주로 사용|거의 사용하지 않음|
|INSERT|데이터 1건|데이터 여러 건|
|UPDATE/DELETE|가능|여러 조건에 반복 적용 가능|
|대량 데이터 저장|비효율적 수 있음|적합|

In [13]:
# 한 행을 삽입하는 경우 : execute()
data = (5, '이방', '010-443-1111', '1981-10-10')

with conn.cursor() as cur:
    sql = 'insert into customer (id, name, tel, birth) values (%s, %s, %s, %s)'
    cur.execute(sql, data)
conn.commit()

In [15]:
# 여러 행을 삽입하는 경우 : executemany()

data_list = [(6, '성춘향', '010-123-3333', '2010-10-10'),
        (7, '이몽룡', '010-444-7777', '2009-05-10')
]

with conn.cursor() as cur:
    sql = 'insert into customer (id, name, tel, birth) values (%s, %s, %s, %s)'
    cur.executemany(sql, data_list)
    #cur.execute(sql, data_list) # TypeError: not enough arguments for format string
conn.commit()

# '%s' : 값이 들어갈 위치를 나타내는 placeholder

In [16]:
# 여러 행을 삽입하는 경우 : execute()
cur = conn.cursor()
data_list = [(8, '강하늘','010-777-3333','2011-10-10'),
             (9, '최장군','010-555-7777','2019-05-10')]
sql = 'insert into customer (id, name, tel, birth) values (%s, %s, %s, %s)'
for data in data_list:
    cur.execute(sql, data)
conn.commit()

#### 7) MySQL 연결 종료 : close()
- **연결자.close()**

In [17]:
conn.close()

### 트랜잭션 처리
- 성공적으로 반영 시 `commit()`, 오류 발생 시 `rollback()`
- DB 연결하고 SQL문을 수행하는 커서 생성하고 데이터 삽입 수행

In [19]:
# DB연결 객체 생성
conn = pymysql.connect(host='127.0.0.1',
                       user = 'crawluser',
                       password = 'acorn1234',
                       db = 'crawlDB',
                       charset='utf8')
# 데이터 준비
data_list = [(10, '성자','010-123-0099','2001-03-10'),
             (11, '방식','010-444-7788','2008-12-10')]
sql = 'insert into customer (id, name, tel, birth) values (%s, %s, %s, %s)'

# 데이터 삽입
try:
    with conn.cursor() as cur:
        cur.executemany(sql, data_list)
    conn.commit()
    print(f'{len(data_list)}행 삽입 완료')
except Exception as e:
    conn.rollback()
    print(f'{e}:오류발생, 롤백')
finally:
    conn.close()

2행 삽입 완료

### 4. 파이썬에서 MySQL 데이터 조회

#### 1) MySQL 연결

In [22]:
conn = pymysql.connect(host='127.0.0.1',
                       user = 'crawluser',
                       password = 'acorn1234',
                       db = 'crawlDB',
                       charset='utf8')

#### 2) cursor 생성

In [23]:
cur = conn.cursor()

#### 3) 조회 SQL문 실행

In [24]:
sql = 'select * from customer'
cur.execute(sql)

11

#### 4) 조회한 데이터 추출

- fetchone() : 한 행씩 데이터 추출
- fetchall() : 모든 행의 데이터 추출
- https://pymysql.readthedocs.io/en/latest/modules/cursors.html

In [25]:
cur.fetchone()

(1, '김바람', '010-123-1111', datetime.date(2000, 1, 1))

In [26]:
cur.fetchone()

(2, '남구름', '010-222-1111', datetime.date(2010, 1, 1))

In [27]:
cur.fetchall()

((3, '서바다', '010-321-2111', datetime.date(2001, 5, 1)),
 (4, '홍하늘', '010-123-1311', datetime.date(2010, 2, 1)),
 (5, '이방', '010-443-1111', datetime.date(1981, 10, 10)),
 (6, '성춘향', '010-123-3333', datetime.date(2010, 10, 10)),
 (7, '이몽룡', '010-444-7777', datetime.date(2009, 5, 10)),
 (8, '강하늘', '010-777-3333', datetime.date(2011, 10, 10)),
 (9, '최장군', '010-555-7777', datetime.date(2019, 5, 10)),
 (10, '성자', '010-123-0099', datetime.date(2001, 3, 10)),
 (11, '방식', '010-444-7788', datetime.date(2008, 12, 10)))

- 반복문을 이용하여 fetchone()으로 모든 행을 추출할 수 있음
- 조회한 결과가 없으면 None 반환

In [30]:
cur.fetchone()
# 이미 앞에서 cur.fetchall() 함수로 모든 행을 추출하여 추출할 자료가 없기 때문에 아무것도 안뜸

In [32]:
cur.execute('select * from customer;')
rows = []
while True:
    row = cur.fetchone() #튜플 형식으로 한 행 가져옴
    dic = {}
    if row is None:
        break
    dic['id'] = row[0]
    dic['name'] = row[1]
    dic['tel'] = row[2]
    dic['birth'] = row[3]
    rows.append(dic)
rows

[{'id': 1,
  'name': '김바람',
  'tel': '010-123-1111',
  'birth': datetime.date(2000, 1, 1)},
 {'id': 2,
  'name': '남구름',
  'tel': '010-222-1111',
  'birth': datetime.date(2010, 1, 1)},
 {'id': 3,
  'name': '서바다',
  'tel': '010-321-2111',
  'birth': datetime.date(2001, 5, 1)},
 {'id': 4,
  'name': '홍하늘',
  'tel': '010-123-1311',
  'birth': datetime.date(2010, 2, 1)},
 {'id': 5,
  'name': '이방',
  'tel': '010-443-1111',
  'birth': datetime.date(1981, 10, 10)},
 {'id': 6,
  'name': '성춘향',
  'tel': '010-123-3333',
  'birth': datetime.date(2010, 10, 10)},
 {'id': 7,
  'name': '이몽룡',
  'tel': '010-444-7777',
  'birth': datetime.date(2009, 5, 10)},
 {'id': 8,
  'name': '강하늘',
  'tel': '010-777-3333',
  'birth': datetime.date(2011, 10, 10)},
 {'id': 9,
  'name': '최장군',
  'tel': '010-555-7777',
  'birth': datetime.date(2019, 5, 10)},
 {'id': 10,
  'name': '성자',
  'tel': '010-123-0099',
  'birth': datetime.date(2001, 3, 10)},
 {'id': 11,
  'name': '방식',
  'tel': '010-444-7788',
  'birth': datetime.date(2008, 12, 10)}]

In [33]:
print(cur.fetchone())

None

#### 5) 추출한 데이터를 데이터프레임으로 생성

In [34]:
import pandas as pd
df = pd.DataFrame(rows)

In [35]:
df

    id name           tel       birth
0    1  김바람  010-123-1111  2000-01-01
1    2  남구름  010-222-1111  2010-01-01
2    3  서바다  010-321-2111  2001-05-01
3    4  홍하늘  010-123-1311  2010-02-01
4    5   이방  010-443-1111  1981-10-10
5    6  성춘향  010-123-3333  2010-10-10
6    7  이몽룡  010-444-7777  2009-05-10
7    8  강하늘  010-777-3333  2011-10-10
8    9  최장군  010-555-7777  2019-05-10
9   10   성자  010-123-0099  2001-03-10
10  11   방식  010-444-7788  2008-12-10

In [37]:
df2 = pd.DataFrame(data=rows, columns=['id', 'name', 'tel', 'birth'])
df2

    id name           tel       birth
0    1  김바람  010-123-1111  2000-01-01
1    2  남구름  010-222-1111  2010-01-01
2    3  서바다  010-321-2111  2001-05-01
3    4  홍하늘  010-123-1311  2010-02-01
4    5   이방  010-443-1111  1981-10-10
5    6  성춘향  010-123-3333  2010-10-10
6    7  이몽룡  010-444-7777  2009-05-10
7    8  강하늘  010-777-3333  2011-10-10
8    9  최장군  010-555-7777  2019-05-10
9   10   성자  010-123-0099  2001-03-10
10  11   방식  010-444-7788  2008-12-10

In [38]:
df.to_csv('crawl_data/customer.csv', index = False)

#### 6) MySQL 연결 종료

In [39]:
conn.close()

**[코드 전체] DB 연결 및 데이터 조회**

In [43]:
#DB 연결
conn = pymysql.connect(host='127.0.0.1',
                       user = 'crawluser',
                       password = 'acorn1234',
                       db = 'crawlDB',
                       charset='utf8')
# 데이터 조회
sql = 'select * from customer;'
colnames = ['id', 'name', 'tel', 'birth']

try:
    with conn.cursor() as cur:
        cur.execute(sql)
        rowss = cur.fetchall()
        print(f'{len(rows)}행 조회')
except Exception as e:
    print(f'조회 실패: {e}')
finally:
    conn.close()


#데이터프레임으로 저장
df4 = pd.DataFrame(data = rowss, columns = colnames)
df4

11행 조회

    id name           tel       birth
0    1  김바람  010-123-1111  2000-01-01
1    2  남구름  010-222-1111  2010-01-01
2    3  서바다  010-321-2111  2001-05-01
3    4  홍하늘  010-123-1311  2010-02-01
4    5   이방  010-443-1111  1981-10-10
5    6  성춘향  010-123-3333  2010-10-10
6    7  이몽룡  010-444-7777  2009-05-10
7    8  강하늘  010-777-3333  2011-10-10
8    9  최장군  010-555-7777  2019-05-10
9   10   성자  010-123-0099  2001-03-10
10  11   방식  010-444-7788  2008-12-10

---

### MySQL 연동을 위한 함수 정의

#### MySQL 연결 함수

In [64]:
def connect_MySQL(host = '127.0.0.1',
                           user = 'crawluser',
                           password = 'acorn1234',
                           database = 'crawlDB',
                           charset='utf8'):
    conn = pymysql.connect(host = host,
                           user = user,
                           password = password,
                           database = database,
                           charset=charset)
    return conn

#### 테이블 조회 함수

In [72]:
def search_table(conn, table_name):
    sql = f'select * from {table_name}'
    try:
        with conn.cursor() as cur:
            cur.execute(sql)
            #print(cur.description)
            colnames = [item[0] for item in cur.description]
            rows = cur.fetchall()
            print(f'{len(rows)}행 조회')
    except Exception as e:
        print(f'조회 실패: {e}')
    finally:
        conn.close()
    
    df = pd.DataFrame(data = rows, columns = colnames)
    print(df)

In [73]:
search_table(connect_MySQL(), 'customer')

(('id', 3, None, 11, 11, 0, False), ('name', 253, None, 20, 20, 0, False), ('tel', 254, None, 39, 39, 0, True), ('birth', 10, None, 10, 10, 0, True))
11행 조회
    id name           tel       birth
0    1  김바람  010-123-1111  2000-01-01
1    2  남구름  010-222-1111  2010-01-01
2    3  서바다  010-321-2111  2001-05-01
3    4  홍하늘  010-123-1311  2010-02-01
4    5   이방  010-443-1111  1981-10-10
5    6  성춘향  010-123-3333  2010-10-10
6    7  이몽룡  010-444-7777  2009-05-10
7    8  강하늘  010-777-3333  2011-10-10
8    9  최장군  010-555-7777  2019-05-10
9   10   성자  010-123-0099  2001-03-10
10  11   방식  010-444-7788  2008-12-10

## sqlalchemy 라이브러리를 이용한 DB연결 및 CRUD

- ORM(Object-Relational Mapping:객체-관계 매핑) 기반으로 데이터베이스 사용
- 테이블과 파이썬 객체를 연결하여 SQL을 직접 작성하지 않고도 DB를 다룰 수 있게 함
| 구분 | PyMySQL | SQLAlchemy |
| :--- | :--- | :--- |
| 역할 | MySQL DB 드라이버 | SQL Toolkit + ORM |
| 지원 DB | 주로 MySQL/MariaDB | MySQL, PostgreSQL, SQLite, Oracle, MS SQL 등 |
| SQL 작성 | 직접 SQL 작성 | 직접 SQL 또는 ORM 방식 |
| 난이도 | 비교적 쉬움 | 상대적으로 높음 |
| DB 연결 | 직접 연결 | Engine을 통해 연결 |
| CRUD | SQL 직접 작성 | SQL 또는 객체기반 CRUD |
| ORM | 지원하지 않음 | 지원 |
| DB 변경 대응 | SQL 수정 필요 | 상대적으로 쉬움 |
| 대규모 프로젝트 | 제한적 | 적합 |
| 학습용 | SQL 학습에 매우 적합 | 웹/백엔드 개발에 적합 |

In [ ]:
# !pip install sqlalchemy

In [ ]:
# PyMySQL 이용한 조회 : SQL문 직접 작성
conn = pymysql.connect(host='127.0.0.1',
                       user = 'crawluser',
                       password = 'acorn1234',
                       db = 'crawlDB',
                       charset='utf8')

sql = 'select * from customer;'
cur = conn.cursor()
cur.execute(sql)
rows = cur.fetchall()
print(f'{len(rows)}행 조회!')
cur.close()
conn.close()

#### DB 연결 : create_engine()

* Engine 객체가 DB 연결 관리
* 연결 문자열 구조

  "mysql+pymysql://사용자:비밀번호@호스트:포트/DB명"

* Engine이 필요할 때마다 DBAPI 연결 얻고 connection pool을 관리함

#### DB 연결 얻기 : connect()

* with문에서 연결을 얻는 경우 with문 블록을 벗어나면 connection이 정리되어 pool로 반환됨
* with문 사용하지 않고 직접 관리하는 경우 close()문을 통해 연결해제해야 함

```python
conn = engine.connect()
conn.close()
```
#### DB 연결 얻기 : begin()
- connect()는 SELECT 문에서 주로 사용
- begin()은 INSERT / DELETE / UPDATE 문에서 사용
- begin()을 사용하면 정상 종료 시 commit이 됨, 오루 발생 시 rollback 수행

In [77]:
# SQLAlchemy 사용한 조회
from sqlalchemy import create_engine, text
engine = create_engine(
    "mysql+pymysql://crawluser:acorn1234@localhost/crawlDB"
)
sql = 'select * from customer;'
with engine.connect() as conn:
    result = conn.execute(
                    text(sql)
    )

    for row in result:
        print(row)

(1, '김바람', '010-123-1111', datetime.date(2000, 1, 1))
(2, '남구름', '010-222-1111', datetime.date(2010, 1, 1))
(3, '서바다', '010-321-2111', datetime.date(2001, 5, 1))
(4, '홍하늘', '010-123-1311', datetime.date(2010, 2, 1))
(5, '이방', '010-443-1111', datetime.date(1981, 10, 10))
(6, '성춘향', '010-123-3333', datetime.date(2010, 10, 10))
(7, '이몽룡', '010-444-7777', datetime.date(2009, 5, 10))
(8, '강하늘', '010-777-3333', datetime.date(2011, 10, 10))
(9, '최장군', '010-555-7777', datetime.date(2019, 5, 10))
(10, '성자', '010-123-0099', datetime.date(2001, 3, 10))
(11, '방식', '010-444-7788', datetime.date(2008, 12, 10))

In [78]:
db_conn_str = "mysql+pymysql://crawluser:acorn1234@localhost/crawlDB"
engine = create_engine(db_conn_str)
conn = engine.connect()

sql = 'select * from customer;'
with engine.connect() as conn:
    rows = conn.execute(
                    text(sql)
    )

    for row in rows:
        print(row)

(1, '김바람', '010-123-1111', datetime.date(2000, 1, 1))
(2, '남구름', '010-222-1111', datetime.date(2010, 1, 1))
(3, '서바다', '010-321-2111', datetime.date(2001, 5, 1))
(4, '홍하늘', '010-123-1311', datetime.date(2010, 2, 1))
(5, '이방', '010-443-1111', datetime.date(1981, 10, 10))
(6, '성춘향', '010-123-3333', datetime.date(2010, 10, 10))
(7, '이몽룡', '010-444-7777', datetime.date(2009, 5, 10))
(8, '강하늘', '010-777-3333', datetime.date(2011, 10, 10))
(9, '최장군', '010-555-7777', datetime.date(2019, 5, 10))
(10, '성자', '010-123-0099', datetime.date(2001, 3, 10))
(11, '방식', '010-444-7788', datetime.date(2008, 12, 10))

조회 메서드

* fetchone() : 한 행 조회
* fetchmany(n) : n개 행 조회
* fetchall() : 전체 행 조회
* all() : 전체 결과 반환
* first() : 첫 번째 행 반환

In [79]:
conn = engine.connect()
sql = text('select * from customer;')
rows = conn.execute(sql)

rows

In [80]:
rows.fetchone()

(1, '김바람', '010-123-1111', datetime.date(2000, 1, 1))

In [81]:
rows.fetchmany(3)

[(2, '남구름', '010-222-1111', datetime.date(2010, 1, 1)),
 (3, '서바다', '010-321-2111', datetime.date(2001, 5, 1)),
 (4, '홍하늘', '010-123-1311', datetime.date(2010, 2, 1))]

In [82]:
rows.first()

(5, '이방', '010-443-1111', datetime.date(1981, 10, 10))

In [86]:
conn.close()

### 조건을 이용한 Select

* 바인드 파라미터를 사용하여 SQL에 값을 바인딩함 (직접 값을 결합하지 않고)
* 형식 : `:변수` => named parameter

In [92]:
sql = text('''
            select * from customer
                where id> :id;
            '''
)

with engine.connect() as conn:
    rows = conn.execute(sql, {"id" : 5})
    for row in rows:
        print(row)

(6, '성춘향', '010-123-3333', datetime.date(2010, 10, 10))
(7, '이몽룡', '010-444-7777', datetime.date(2009, 5, 10))
(8, '강하늘', '010-777-3333', datetime.date(2011, 10, 10))
(9, '최장군', '010-555-7777', datetime.date(2019, 5, 10))
(10, '성자', '010-123-0099', datetime.date(2001, 3, 10))
(11, '방식', '010-444-7788', datetime.date(2008, 12, 10))

```python
# PyMySQL 방식
cur.execute(
    "select * from customer where id > %s", (5,)
)

# SQLAlchemy
conn.execute(
    text("select * from customer where id > :id", {'id':5})
)
```

#### 데이터 삽입 INSERT

In [98]:
sql = text('''
            insert into customer (id, name, tel, birth)
                values (:id, :name, :tel, :birth)
''')

with engine.begin() as conn:
    conn.execute(sql, 
        {'id':'12', 'name':'방자형','tel':'010-100-1000','birth':'2020-10-01'}
    )
    rows = conn.execute(text("select * from customer"))
    for row in rows:
        print(row)

(1, '김바람', '010-123-1111', datetime.date(2000, 1, 1))
(2, '남구름', '010-222-1111', datetime.date(2010, 1, 1))
(3, '서바다', '010-321-2111', datetime.date(2001, 5, 1))
(4, '홍하늘', '010-123-1311', datetime.date(2010, 2, 1))
(5, '이방', '010-443-1111', datetime.date(1981, 10, 10))
(6, '성춘향', '010-123-3333', datetime.date(2010, 10, 10))
(7, '이몽룡', '010-444-7777', datetime.date(2009, 5, 10))
(8, '강하늘', '010-777-3333', datetime.date(2011, 10, 10))
(9, '최장군', '010-555-7777', datetime.date(2019, 5, 10))
(10, '성자', '010-123-0099', datetime.date(2001, 3, 10))
(11, '방식', '010-444-7788', datetime.date(2008, 12, 10))
(12, '방자형', '010-100-1000', datetime.date(2020, 10, 1))
(13, '방자형', '010-100-1000', datetime.date(2020, 10, 1))

In [100]:
customers = [
    #{'id':'13', 'name':'방자형','tel':'010-101-1001','birth':'2020-10-01'},
    {'id':'14', 'name':'형',  'tel':'010-100-1002','birth':'2010-10-01'},
    {'id':'15', 'name':'아우','tel':'010-100-1030','birth':'2015-10-01'},
]

sql = text('''
    insert into customer (id, name, tel, birth)
    values (:id, :name, :tel, :birth)
''')

with engine.begin() as conn:
    conn.execute(sql, customers)
    
    rows = conn.execute(text("select * from customer"))
    for row in rows:
        print(row)

(1, '김바람', '010-123-1111', datetime.date(2000, 1, 1))
(2, '남구름', '010-222-1111', datetime.date(2010, 1, 1))
(3, '서바다', '010-321-2111', datetime.date(2001, 5, 1))
(4, '홍하늘', '010-123-1311', datetime.date(2010, 2, 1))
(5, '이방', '010-443-1111', datetime.date(1981, 10, 10))
(6, '성춘향', '010-123-3333', datetime.date(2010, 10, 10))
(7, '이몽룡', '010-444-7777', datetime.date(2009, 5, 10))
(8, '강하늘', '010-777-3333', datetime.date(2011, 10, 10))
(9, '최장군', '010-555-7777', datetime.date(2019, 5, 10))
(10, '성자', '010-123-0099', datetime.date(2001, 3, 10))
(11, '방식', '010-444-7788', datetime.date(2008, 12, 10))
(12, '방자형', '010-100-1000', datetime.date(2020, 10, 1))
(13, '방자형', '010-100-1000', datetime.date(2020, 10, 1))
(14, '형', '010-100-1002', datetime.date(2010, 10, 1))
(15, '아우', '010-100-1030', datetime.date(2015, 10, 1))

#### 데이터 갱신 : update

In [101]:
sql = text('''
    update customer set name = :name where id = :id
''')

with engine.begin() as conn:
    result = conn.execute(sql, {'name': '방우형',
                                'id': '13'})

    print(result.rowcount)

1

In [102]:
with engine.begin() as conn:
    rows = conn.execute(text("select * from customer"))
    for row in rows:
        print(row)

(1, '김바람', '010-123-1111', datetime.date(2000, 1, 1))
(2, '남구름', '010-222-1111', datetime.date(2010, 1, 1))
(3, '서바다', '010-321-2111', datetime.date(2001, 5, 1))
(4, '홍하늘', '010-123-1311', datetime.date(2010, 2, 1))
(5, '이방', '010-443-1111', datetime.date(1981, 10, 10))
(6, '성춘향', '010-123-3333', datetime.date(2010, 10, 10))
(7, '이몽룡', '010-444-7777', datetime.date(2009, 5, 10))
(8, '강하늘', '010-777-3333', datetime.date(2011, 10, 10))
(9, '최장군', '010-555-7777', datetime.date(2019, 5, 10))
(10, '성자', '010-123-0099', datetime.date(2001, 3, 10))
(11, '방식', '010-444-7788', datetime.date(2008, 12, 10))
(12, '방자형', '010-100-1000', datetime.date(2020, 10, 1))
(13, '방우형', '010-100-1000', datetime.date(2020, 10, 1))
(14, '형', '010-100-1002', datetime.date(2010, 10, 1))
(15, '아우', '010-100-1030', datetime.date(2015, 10, 1))

#### 데이터 삭제 DELETE

In [ ]:
sql = text('''
    delete from customer where id = :id
''')

with engine.begin() as conn:
    result = conn.execute(sql, {'id':'13'})
    print(result.rowcount)
    
    rows = conn.execute(text("select * from customer"))
    for row in rows:
        print(row)

#### 트랜잭션

In [104]:
sql1 = text('''
    insert into customer (id, name, tel, birth)
    values (:id, :name, :tel, :birth)
''')

with engine.connect() as conn:
    #connect()로 실행하면
    conn.execute(sql1, 
        {'id':'13', 'name':'방자형', 'tel':'010-101-1001', 'birth':'2020-10-01'}
    )
    # commit 직접 해야함
    conn.commit()
    
    rows = conn.execute(text("select * from customer"))
    for row in rows:
        print(row)

(1, '김바람', '010-123-1111', datetime.date(2000, 1, 1))
(2, '남구름', '010-222-1111', datetime.date(2010, 1, 1))
(3, '서바다', '010-321-2111', datetime.date(2001, 5, 1))
(4, '홍하늘', '010-123-1311', datetime.date(2010, 2, 1))
(5, '이방', '010-443-1111', datetime.date(1981, 10, 10))
(6, '성춘향', '010-123-3333', datetime.date(2010, 10, 10))
(7, '이몽룡', '010-444-7777', datetime.date(2009, 5, 10))
(8, '강하늘', '010-777-3333', datetime.date(2011, 10, 10))
(9, '최장군', '010-555-7777', datetime.date(2019, 5, 10))
(10, '성자', '010-123-0099', datetime.date(2001, 3, 10))
(11, '방식', '010-444-7788', datetime.date(2008, 12, 10))
(12, '방자형', '010-100-1000', datetime.date(2020, 10, 1))
(13, '방자형', '010-101-1001', datetime.date(2020, 10, 1))
(14, '형', '010-100-1002', datetime.date(2010, 10, 1))
(15, '아우', '010-100-1030', datetime.date(2015, 10, 1))

DB 연결 해제

* connection은 with를 사용하는 것이 가장 바람직. with 블록이 종료되면 connection 종료
* connection을 명시적으로 종료하려면

  ```python
  conn.close()

In [ ]:
engine.dispose()

### SQLAlchemy의 Core 방식을 이용한 CRUD
- DB의 테이블과 컬럼을 SQLAlchemy 객체로 표현해서 SQL을 구성하는 방식
```
SQLAlchemy
├─ Core
   ├─ Engine
   ├─ Connection
   ├─ MetaData
   ├─ Table
   ├─ Column
   └─ select(), insert(), update(), delete()
```

In [3]:
# SQLAlchemy의 Core 방식
from sqlalchemy import create_engine,  MetaData, Table, Column, Integer, String, select
 
# DB 연결
engine = create_engine(
    "mysql+pymysql://crawluser:acorn1234@localhost/crawlDB"
)
 
# MetaData
metadata = MetaData()
 
# Table 정의
member = Table("member", metadata,
                Column(
                    "id",
                    Integer,
                    primary_key=True,
                    autoincrement=True
                ),           
                Column(
                    "name",
                    String(50),
                    nullable=False
                ),
                Column(
                    "age",
                    Integer
                )
)
 
# 테이블 생성
metadata.create_all(engine)

In [4]:
# Insert
with engine.begin() as conn:
    mem = member.insert().values(
        name="홍길동",
        age=25
    )
    conn.execute(mem)
 
# Select
with engine.connect() as conn:
    mem = select(member)
    result = conn.execute(mem)
    for row in result:
        print(row)
        
# Update
with engine.begin() as conn:
    mem = (
        member.update()
        .where(member.c.name == "홍길동")
        .values(age=30)
    )
    conn.execute(mem)
 
# Delete
with engine.begin() as conn:
    mem = (
        member.delete()
        .where(member.c.name == "홍길동")
    )
    conn.execute(mem)
 
# 연결 해제
engine.dispose()

(1, '홍길동', 25)

In [7]:
from sqlalchemy import create_engine, String, select
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, Session

# 1. DB 연결
engine = create_engine(
    "mysql+pymysql://crawluser:acorn1234@localhost/crawlDB" ),
    echo=True
)
 
 
# 2. ORM Base 클래스 정의
class Base(DeclarativeBase):
    pass
 
# 3. ORM 클래스 정의
#    Student 클래스  student 테이블
 
class Student(Base):
    __tablename__ = "student"
 
    id: Mapped[int] = mapped_column(
        primary_key=True,
        autoincrement=True
    )
 
    name: Mapped[str] = mapped_column(
        String(50),
        nullable=False
    )
 
    age: Mapped[int] = mapped_column()
 
 
 
# 4. 테이블 생성
Base.metadata.create_all(engine)

IndentationError: unexpected indent (2919955339.py, line 7)

In [5]:
# 5. CREATE - 데이터 추가

with Session(engine) as session:
    student = Student(
        name="홍길동",
        age=25
    )
 
    session.add(student)
    session.commit()
    print("INSERT 완료") 

# 6. READ - 전체 조회
with Session(engine) as session:
    stmt = select(Student)
    students = session.scalars(stmt).all()
    print("\n[전체 학생 조회]")

    for student in students:
        print(
            student.id,
            student.name,
            student.age
        )
 
 
# 7. UPDATE - 데이터 수정
with Session(engine) as session:
    student = session.get(Student, 1)
    if student:
        student.age = 30
        session.commit()
 
        print("\nUPDATE 완료")
 
 
# 8. DELETE - 데이터 삭제
with Session(engine) as session:
    student = session.get(Student, 1)
    if student:
        session.delete(student)
        session.commit()
 
        print("DELETE 완료")
 
 
# 9. DB 연결 Pool 정리
engine.dispose()
engine = create_engine(
    "mysql+pymysql://crawluser:acorn1234@localhost/crawlDB" )

NameError: name 'Session' is not defined