## 파이썬과 MySQL 연동 #2

## 쇼핑몰 사이트 크롤링한 데이터 MySQL DB에 저장하고 조회하기

In [19]:
import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pymysql
import pandas as pd
import time

### DB 연동 순서

1. DB 연동 준비
    - MySQL 연결 및 cursor 생성
    - shopdb 생성
    - table 생성
2. 크롤링 & DB 저장
    - 크롤링: 데이터를 table 형식에 맞게 정제
    - 데이터 insert & commit() 해서 db에 반영
3. DB 테이블 조회 및 추출
    - 테이블 조회: select
    - 데이터 추출: fetchall
    - 추출 데이터 csv 파일 또는 데이터프레임에 저장
4. MySQL 연결 종료

## #1. DB 연동 준비
- 데이터베이스 shopdb2 생성
- 테이블 product 생성

#### 1-1. MySQL 연결 및 cursor 객체 생성

In [36]:
host, port, user, pw = 'localhost', 3306, 'root', 'acorn1234'

conn = pymysql.connect(host=host,
                       port=port,
                       user=user,
                       password=pw,
                       charset='utf8mb4')

cur = conn.cursor()

In [3]:
cur.execute('show databases;')
cur.fetchall()

(('bookdb',),
 ('crawldb',),
 ('exdb',),
 ('information_schema',),
 ('marketdb',),
 ('mysql',),
 ('performance_schema',),
 ('sakila',),
 ('shopdb',),
 ('sys',),
 ('testdb2',),
 ('uniondb',),
 ('world',))

#### 1-2. 데이터베이스 shopdb 생성

In [6]:
sql_list = ['drop database if exists crawlDB;',
            'create database crawlDB default character set utf8mb4;']
for sql in sql_list:
    cur.execute(sql)

# cur.execute('show tables from crawlDB;')
# cur.fetchall()

()

In [7]:
sql = 'use crawldb'
cur.execute(sql)

0

In [8]:
sql = 'select database();'
cur.execute(sql)
cur.fetchone()

('crawldb',)

#### 1-3. Table 생성

- 'shopdb' 데이터베이스 선택

- 테이블 'product' 생성

In [10]:
sqls = ['drop table if exists product;',
        '''create table product (
            prdId int auto_increment not null,
            name varchar(300) not null,
            price varchar(20),
            salePrice varchar(20),
            salePct varchar(10),
            link varchar(300),
            primary key(prdId)
        );'''
]
try:
    for sql in sqls:
        cur.execute(sql)

    conn.commit()                    # DB저장소에 물리적으로 저장 : 저장디스크 I/O작업 수행
    print('product 테이블 생성 완료!')
    
except Exception as e:
    conn.rollback()
    print(f'테이블 생성 오류: {e}')

product 테이블 생성 완료!

- 테이블 목록 조회

In [11]:
cur.execute('show tables;')
cur.fetchall()

(('product',),)

- product 테이블 정보 조회

In [12]:
cur.execute('desc product;')
cur.fetchall()

(('prdId', 'int', 'NO', 'PRI', None, 'auto_increment'),
 ('name', 'varchar(300)', 'NO', '', None, ''),
 ('price', 'varchar(20)', 'YES', '', None, ''),
 ('salePrice', 'varchar(20)', 'YES', '', None, ''),
 ('salePct', 'varchar(10)', 'YES', '', None, ''),
 ('link', 'varchar(300)', 'YES', '', None, ''))

In [13]:
conn.close()

#### 1-4. DB생성 + table 생성 함수

In [15]:
def createDB_and_table():
    host, port, user, pw = 'localhost', 3306, 'root', 'acorn1234'
    sql_list = ['drop database if exists crawlDB;',
                'create database crawlDB default character set utf8mb4;',
                'use crawlDB;',
                'drop table if exists product;',
                '''create table product (
                    prdId int auto_increment not null,
                    name varchar(300) not null,
                    price varchar(20),
                    salePrice varchar(20),
                    salePct varchar(10),
                    link varchar(300),
                    primary key(prdId)
                );
                '''
    ]
    try:
        # MySQL 연결
        conn = pymysql.connect(host=host,   port=port,
                               user=user,   password=pw,
                               charset='utf8mb4')
        print('MySQL 연결 성공!')
        with conn.cursor() as cur:
            # DB & table 생성
            for sql in sql_list:
                cur.execute(sql)
                time.sleep(1)    # 서버 부하 감소!
            cur.execute('desc product;')
            result = cur.fetchall()
            print(f'테이블 product 정보:\n{result}')
        conn.commit()
        print('product 테이블 생성 완료!')
            
    except Exception as e:
        conn.rollback()
        print(f'오류발생:{e}')
    finally:
        conn.close()
        print('MySQL 접속 종료!')

In [16]:
createDB_and_table()

MySQL 연결 성공!
테이블 product 정보:
(('prdId', 'int', 'NO', 'PRI', None, 'auto_increment'), ('name', 'varchar(300)', 'NO', '', None, ''), ('price', 'varchar(20)', 'YES', '', None, ''), ('salePrice', 'varchar(20)', 'YES', '', None, ''), ('salePct', 'varchar(10)', 'YES', '', None, ''), ('link', 'varchar(300)', 'YES', '', None, ''))
product 테이블 생성 완료!
MySQL 접속 종료!

---

## #2. 크롤링 & DB에 저장
: 크롤링한 데이터를 테이블에 insert

### 쇼핑몰 크롤링 데이터 DB 저장 방식

#### 방식1. 웹 페이지 별로 크롤링하고 바로 DB에 저장
- 장점
    - **실시간 저장** : 크롤링한 데이터 즉시 DB 반영
    - **메모리 부담 낮음** : 크롤링할 때 마다 삽입하므로 메모리에 데이터 누적되지 않음
    - 복구 용이 : 크롤링 도중 프로그램 중단되어도 저장된 데이터는 남아 있음
- 단점
    - DB 연결/삽입 횟수 증가로 **성능 저하** 가능(특히 레코드가 많을 경우)
    - 삽입 시 오류가 나면 크롤링과 저장 로직이 엉킬 수 있음
    - commit을 자주해야 하므로 트랜잭션 비용 증
- 이용 상황
    - 소량의 데이터 또는 실시간 처리가 필요한 경우
    - 네트워크나 크롤링 실패 위험이 큰 경우

#### 방식2. 모든 웹페이지 데이터를 모두 수집한 뒤 한번에 DB에 저장
- 장점
    - 성능 최적화 가능 : 크롤링은 빠르게 하고, executemany()로 대량 저장
    - I/O비용 감소 : DB와의 연결은 한 번만 하므로
    - 삽입 전에 데이터를 정제/검증/필터링할 수 있어 가공된 데이터 저장 가능
- 단점
    - 메모리 사용량 증가 : 데이터 수집하는 동안 메모리에 계속 보관해야 함
    - 크롤링 도중 에러나 인터럽트 발생 시 모든 데이터 손실 가능성 존재
    - 저장하기 전까지 아무것도 DB에 남지 않음 (중간 장애 발생 시 문제됨)
- 이용 상황
    - 대량의 데이터 또는 성능 최우선인 경우
    - 데이터 정제/검증 후 저장이 필요한 경우

#### 크롤링 페이지 url목록 생성

In [25]:
def get_product_urls():
    url = 'https://jolse.com/category/serums/1019/'  # Mist & Toner
    headers = {'User-Agent':'Mozilla/5.0'}
    html = requests.get(url, headers=headers).text
    soup = BeautifulSoup(html, 'html.parser')
    last = soup.find('a', {'class':'last'})['href'].split('=')
    page = last[0]
    lastNo = last[-1]
    return [f'{url}{page}={i}' for i in range(1,int(lastNo)+1)]

get_product_urls()

['https://jolse.com/category/serums/1019/?page=1',
 'https://jolse.com/category/serums/1019/?page=2',
 'https://jolse.com/category/serums/1019/?page=3',
 'https://jolse.com/category/serums/1019/?page=4',
 'https://jolse.com/category/serums/1019/?page=5',
 'https://jolse.com/category/serums/1019/?page=6',
 'https://jolse.com/category/serums/1019/?page=7',
 'https://jolse.com/category/serums/1019/?page=8',
 'https://jolse.com/category/serums/1019/?page=9',
 'https://jolse.com/category/serums/1019/?page=10',
 'https://jolse.com/category/serums/1019/?page=11',
 'https://jolse.com/category/serums/1019/?page=12']

In [23]:
def get_products_info(soup):
    prdList = soup.find('ul', {'class':'prdList grid5'})
    items = prdList.find_all('div', {'class':'description'})
    prd_info_list = [get_product_info(item) for item in items]
    return prd_info_list

### 2-1. 웹 페이지별로 크롤링한 후 DB에 저장

- 1개 상품의 이름, 정상가, 세일가, 링크 정보 추출하는 함수 정의

In [24]:
def get_product_info(item):
    # 상품명 추출
    prdBox = item.find('strong', {'class':'name'})
    prdName = prdBox.find_all('span')[-1].text
    # 상품가격 추출
    ul = item.find('ul')
    priceInfo = ul.find_all('span')
        
    # 정상가 추출
    price = priceInfo[1].text
    # 세일가 추출
    try:
        saleinfo = priceInfo[4].text.split('(')
        salePrice = saleinfo[0].strip()
        salePct = saleinfo[-1].rstrip(' OFF)')
    except:
        salePrice = ''
        salePct = '0%'
    # 상품링크 : 상세페이지주소
    link = prdBox.a['href']
    
    return prdName, price, salePrice, salePct, link

- 한 페이지에 들어있는 상품목록 추출 함수 정의

In [27]:
def crawl_products_page(url):
    headers = {'User-Agent':'Mozilla/5.0'}
    html = requests.get(url, headers=headers).text
    soup = BeautifulSoup(html, 'html.parser')
    prdList = soup.find('ul', {'class':'prdList grid5'})
    items = prdList.find_all('div', {'class':'description'})
    return [get_product_info(item) for item in items]

In [28]:
url = 'https://jolse.com/category/serums/1019/?page=1'
result = crawl_products_page(url)
len(result), result[0]

(40,
 ('Dr.Althea 345 Relief Cream Mist 100ml',
  'USD 24.00',
  'USD 16.80',
  '30%',
  '/product/dralthea-345-relief-cream-mist-100ml/92356/category/1019/display/1/'))

- 크롤링 데이터를 DB table에 저장하기

In [29]:
def insert_data(conn, prdList):
    try:
        with conn.cursor() as cur:
            sql = '''
                insert into product
                    (name, price, salePrice, salePct, link)
                values (%s, %s, %s, %s, %s);'''
            cur.executemany(sql, prdList)
        conn.commit()
        print(f'{len(prdList)}행 삽입 성공!')
    except Exception as e:
        conn.rollback()
        print(f'오류발생!: {e}')

- 크롤링 & DB 저장

In [38]:
def mysql_connet(host_info:dict):
    '''
        host_info : dict
    '''
    try:
        conn = pymysql.connect(host=host_info['host'],
                               port=host_info['port'],
                               user=host_info['user'],
                               password=host_info['passwd'],
                               database=host_info['database'],
                               charset=host_info['charset'],
                              )
        print(f'MySQL {host_info["database"]} 접속 성공')
        
    except Exception as e:
        print(f'오류:{e}')
    return conn

In [42]:
host_info = {'host':'localhost',
             'port':3306,
             'user':'root',
             'passwd':'acorn1234',
             'database':'crawlDB',
             'charset':'utf8mb4'}
conn = mysql_connet(host_info)

MySQL crawlDB 접속 성공

In [40]:
conn.close()

In [43]:
url = 'https://jolse.com/category/serums/1019/?page=1'
result = crawl_products_page(url)
insert_data(conn, result)
conn.close()

40행 삽입 성공!

In [49]:
def crawl_and_storeDB():
    # 1단계. DB 접속 
    host_info = {'host':'localhost',
                 'port':3306,
                 'user':'root',
                 'passwd':'acorn1234',
                 'database':'crawlDB',
                 'charset':'utf8mb4'}
    conn = mysql_connet(host_info)
    # 2단계. 크롤링하려는 웹페이지 목록 생성
    url_list = get_product_urls()
    page_n = len(url_list)
    all_data = []
    
    # 3단계. 모든페이지 크롤링
    for i, url in enumerate(url_list):
        try:
            result = crawl_products_page(url)
            all_data.extend(result)
            
            print(f'{i+1}/{page_n} page 크롤링 후 데이터삽입')
            time.sleep(1)
        except Exception as e:
            print(f'{url}->{e}: 에러 발생')
            
    # 4단계. product 테이블에 크롤링한 전체 데이터 삽입
    try:
        insert_data(conn, all_data)
    except Except as e:
        print(f'데이터 삽입 에러: {e}')
    print('모든 페이지 저장 완료')
    conn.close()
    print('MySQL DB 접속 종료')

### 2-2. 모든 페이지 크롤링한 후 한번에 DB 저장

- 지정한 페이지의 전체 상품목록을 db 테이블에 저장하는 함수 정의

In [50]:
createDB_and_table()
print('-'*30)
crawl_and_storeDB()

MySQL 연결 성공!
테이블 product 정보:
(('prdId', 'int', 'NO', 'PRI', None, 'auto_increment'), ('name', 'varchar(300)', 'NO', '', None, ''), ('price', 'varchar(20)', 'YES', '', None, ''), ('salePrice', 'varchar(20)', 'YES', '', None, ''), ('salePct', 'varchar(10)', 'YES', '', None, ''), ('link', 'varchar(300)', 'YES', '', None, ''))
product 테이블 생성 완료!
MySQL 접속 종료!
------------------------------
MySQL crawlDB 접속 성공
1/12 page 크롤링 후 데이터삽입
2/12 page 크롤링 후 데이터삽입
3/12 page 크롤링 후 데이터삽입
4/12 page 크롤링 후 데이터삽입
5/12 page 크롤링 후 데이터삽입
6/12 page 크롤링 후 데이터삽입
7/12 page 크롤링 후 데이터삽입
8/12 page 크롤링 후 데이터삽입
9/12 page 크롤링 후 데이터삽입
10/12 page 크롤링 후 데이터삽입
11/12 page 크롤링 후 데이터삽입
12/12 page 크롤링 후 데이터삽입
470행 삽입 성공!
모든 페이지 저장 완료
MySQL DB 접속 종료

----

---

### #3. 저장한 데이터베이스 테이블 조회(select) 및 추출

In [87]:
def select_table(conn, table):
    with conn.cursor() as cur:
        sql = f'select * from {table}'
        cur.execute(sql)
        result = cur.fetchall()
        print(f'{len(result)}행 조회')
    return result

In [88]:
host_info = {'host':'localhost',
             'port':3306,
             'user':'root',
             'database':'crawlDB',
             'passwd':'acorn1234',
             'charset':'utf8mb4'}
conn = mysql_connet(host_info)
data_rows = select_table(conn, 'product')
conn.close()

MySQL crawlDB 접속 성공
470행 조회

In [86]:
data_rows[0]

(1,
 'Dr.Althea 345 Relief Cream Mist 100ml',
 'USD 24.00',
 'USD 16.80',
 '30%',
 '/product/dralthea-345-relief-cream-mist-100ml/92356/category/1019/display/1/')

#### product 테이블에 저장된 데이터 df로 가져오기

#### sql문으로 조회한 데이터를 데이터 프레임으로 저장

In [81]:
def get_table_data(conn, table):
    with conn.cursor() as cur:
        sql = f'select * from {table}'
        cur.execute(sql)
        result = cur.fetchall()
        column_names = [col[0] for col in cur.description]
        df = pd.DataFrame(result, columns = column_names)
        
    return df

In [82]:
conn = mysql_connet(host_info)
data = get_data(conn, 'product')
data

MySQL crawlDB 접속 성공

,prdId,name,price,salePrice,salePct,link
0,1,Dr.Althea 345 Relief Cream Mist 100ml,USD 24.00,USD 16.80,30%,/product/dralthea-345-relief-cream-mist-100ml/...
1,2,[🐳1+1] Anua Rice 70 Glow Milky Toner 150ml,USD 44.00,USD 27.99,36%,/product/🐳11-anua-rice-70-glow-milky-toner-150...
2,3,B : Lab Essence Toner Pad 10ea/25g,USD 5.00,USD 2.30,54%,/product/b-lab-essence-toner-pad-10ea25g/89277...
3,4,Anua Rice 70 Glow Milky Toner 150ml,USD 22.00,USD 16.50,25%,/product/anua-rice-70-glow-milky-toner-150ml/9...
4,5,[🐳1+1] Dr.Althea 345 Relief Cream Mist 100ml,USD 48.00,USD 33.60,30%,/product/🐳11-dralthea-345-relief-cream-mist-10...
...,...,...,...,...,...,...
465,466,ONE THING Centella Asiatica Extract 150ml,USD 20.54,USD 12.32,40%,/product/one-thing-centella-asiatica-extract-1...
466,467,LANEIGE Perfect Renew Youth Refiner 120ml,USD 47.16,USD 35.84,24%,/product/laneige-perfect-renew-youth-refiner-1...
467,468,SOME BY MI AHA BHA PHA 30 Days Miracle Toner 1...,USD 22.57,USD 19.18,15%,/product/some-by-mi-aha-bha-pha-30-days-miracl...
468,469,MISSHA Perfumed shower Cologne 105ml,USD 13.00,USD 11.05,15%,/product/missha-perfumed-shower-cologne-105ml/...
469,470,numbuzin No.9 NAD+ PDRN Glow Boosting Toner 150ml,USD 25.00,USD 21.25,15%,/product/numbuzin-no9-nad-pdrn-glow-boosting-t...

#### product 테이블에 저장된 데이터 df로 가져오기

In [89]:
sql = 'select * from product;'
conn = mysql_connet(host_info)
df2 = pd.read_sql(sql, conn)
conn.close()
df2.head()

MySQL crawlDB 접속 성공

C:\Users\acorn2\AppData\Local\Temp\ipykernel_3844\3517709077.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql(sql, conn)

,prdId,name,price,salePrice,salePct,link
0,1,Dr.Althea 345 Relief Cream Mist 100ml,USD 24.00,USD 16.80,30%,/product/dralthea-345-relief-cream-mist-100ml/...
1,2,[🐳1+1] Anua Rice 70 Glow Milky Toner 150ml,USD 44.00,USD 27.99,36%,/product/🐳11-anua-rice-70-glow-milky-toner-150...
2,3,B : Lab Essence Toner Pad 10ea/25g,USD 5.00,USD 2.30,54%,/product/b-lab-essence-toner-pad-10ea25g/89277...
3,4,Anua Rice 70 Glow Milky Toner 150ml,USD 22.00,USD 16.50,25%,/product/anua-rice-70-glow-milky-toner-150ml/9...
4,5,[🐳1+1] Dr.Althea 345 Relief Cream Mist 100ml,USD 48.00,USD 33.60,30%,/product/🐳11-dralthea-345-relief-cream-mist-10...

#### sql문으로 조회한 데이터를 데이터 프레임으로 저장

In [83]:
def read_sql(sql, conn):
    with conn.cursor() as cur:
        data = get_table_data(conn, 'product')
        column_names = [col[0] for col in cur.description]
    column_names = [col[0] for col in cur.description]
    df = pd.DataFrame(result, columns = column_names)
        
    return df
    
conn = mysql_connect(host_info)
sql = 'select * from product;'

conn.execute(sql)
data = conn.fetchall()

df2 = pd.read_sql(sql, conn)
conn.close()
df2.head()

NameError: name 'mysql_connect' is not defined

In [ ]:
sqlAlchemy를 이용한 DB연결 및 테이블 조회

---

In [92]:
from sqlalchemy import create_engine

db_conn_str = 'mysql+pymysql://root:acorn1234@localhost/crawlDb?charset=utf8mb4'
engine = create_engine(db_conn_str)
conn = engine.connect()

sql = 'select * from product;'

df3 = pd.read_sql(sql, conn)
conn.close()
engine.dispose()
df3.head()

,prdId,name,price,salePrice,salePct,link
0,1,Dr.Althea 345 Relief Cream Mist 100ml,USD 24.00,USD 16.80,30%,/product/dralthea-345-relief-cream-mist-100ml/...
1,2,[🐳1+1] Anua Rice 70 Glow Milky Toner 150ml,USD 44.00,USD 27.99,36%,/product/🐳11-anua-rice-70-glow-milky-toner-150...
2,3,B : Lab Essence Toner Pad 10ea/25g,USD 5.00,USD 2.30,54%,/product/b-lab-essence-toner-pad-10ea25g/89277...
3,4,Anua Rice 70 Glow Milky Toner 150ml,USD 22.00,USD 16.50,25%,/product/anua-rice-70-glow-milky-toner-150ml/9...
4,5,[🐳1+1] Dr.Althea 345 Relief Cream Mist 100ml,USD 48.00,USD 33.60,30%,/product/🐳11-dralthea-345-relief-cream-mist-10...

---