# pandas 다중 인덱스(multi index)

In [1]:
# 필요 모듈
import numpy as np
import pandas as pd

print(f'numpy : {np.__version__}, pandas : {pd.__version__}')

numpy : 2.5.2, pandas : 3.0.5

In [2]:
# 여러 변수 출력 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
# import warnings
# warnings.filterwarnings('ignore')

### 참고. 난수 생성 : np.random 모듈


##### np.random.seed(seed값)

- seed : 난수 알고리즘에서 사용하는 기본 값
    - seed 값이 같으면 동일한 난수 발생
    - 예. np.random.seed(10) 


- 계속 변경되는 난수를 생성하려면 시드값이 매번 변하도록 지정
    - 예. np.random.seed(int(time.time()))
    

#### 난수 생성 함수

- np.random.rand() : 주어진 형태의 난수 배열 생성
- np.random.randint(최소값, 최대값, size=n) 
    - [최소값, 최대값)의 범위에서 임의의 정수 생성
    
- np.random.randn() : 표준정규분포(Standard normal distribution)로부터 샘플링된 난수 생성

- np.random.standard_normal() : 표준정규분포 난수 발생

- np.random.normal([loc, scale, size]) : 정규분포 난수 생성

- np.random.random_sample(size) : [0,1)사이의 난수 생성

- np.random.choice(a[, size, replace, p]) : 주어진 배열로 부터 표본추출

In [6]:
# 시드 값 고정
np.random.seed(10)
np.random.randint(1,7, size=10)

array([2, 6, 5, 1, 2, 4, 5, 2, 6, 1], dtype=int32)

In [7]:
import time

print(time.time())
np.random.seed(int(time.time()))

1788239664.7417257

In [10]:
np.random.randint(1,7, size=10)

array([2, 4, 2, 4, 3, 5, 1, 1, 1, 3], dtype=int32)

In [13]:
np.random.rand() # 0~1 사이의 실수난수 (균일분포 난수)
np.random.randn() # 표준정규분포 난수 (평균 0, 표준편차 1)
np.random.choice(['r','g','b','y','d'], size =2)

0.7020708499812587

array(['d', 'r'], dtype='<U1')

### 참고. 파이썬의 random 모듈

https://docs.python.org/ko/3/library/random.html

#### 정수 난수 발생 함수

##### random.randrange(start, stop[, step])
- range(start, stop, step)에서 임의로 선택된 요소를 반환
- choice(range(start, stop, step))와 동등하지만 실제로 range 객체를 만들지는 않음

##### random.randint(a, b)
- `a <= N <= b` 를 만족하는 임의의 정수 N을 반환
- randrange(a, b+1)의 별칭

#### 시퀀스 난수 발생 함수
##### random.choice(seq)
- 비어 있지 않은 시퀀스 seq에서 임의의 요소를 반환
- seq가 비어 있으면, IndexError를 발생


##### random.choices(population, weights=None, *, cum_weights=None, k=1)
- population에서 중복을 허락하면서(with replacement) 선택한 k 크기의 요소 리스트를 반환
- population이 비어 있으면 IndexError 발생
- weights 시퀀스가 지정되면 상대 가중치에 따라 선택됨
- weights나 cum_weights를 지정하지 않으면 같은 확률로 선택
- weights 시퀀스가 제공되면, population 시퀀스와 길이가 같아야 함
- weights와 cum_weights를 모두 지정하는 것은 TypeError

##### random.sample(population, k, *, counts=None)
- population 시퀀스로부터 추출한 k개 길이의 새 리스트를 반환
- random sampling without replacement

#### 실수 난수 발생 함수
##### random.random()
- `0.0 <= X < 1.0` 사이의 실수 반환

##### random.uniform(a, b)
- `a <= b` 일 때 `a <= N <= b`, `b < a` 일 때 `b <= N <= a`를 만족하는 임의의 부동 소수점 숫자 N을 반환
- 종단 값 b는 방정식 a + (b-a) * random()의 부동 소수점 자리 올림에 따라 범위에 포함되거나 포함되지 않을 수 있음

----

## 다중 인덱스(multi index)란?
- 행이나 열 인덱스가 계층으로 구성된 인덱스(Hierarchical indexing)

In [17]:
df= pd.DataFrame([[1,2,3,4],
                  [2,3,4,5]],
                 columns = list('ABCD'),
                 index = [['a','b']]
                 )

[학습 내용]

1. 다중 인덱스를 갖는 Series
2. 다중 인덱스를 갖는 DataFrame
3. MultiIndex 객체
4. 다중인덱스의 특정 레벨 제거 : droplevel()
5. 행인덱스 레벨 해제 : unstack()
6. 열인덱스 레벨 해제 : stack()
7. 다중인덱스의 레벨 교환 : swaplevel()
8. 다중인덱스의 행/열 추가
9. 다중인덱스 정렬

### 1. 다중인덱스를 갖는 Series

#### 예1. 난수 데이터를 갖는 Series

In [22]:
arrays = [np.array(["bar", "bar", "baz", "baz",
                    "foo", "foo", "qux", "qux"]),
          np.array(["one", "two", "one", "two",
                    "one", "two", "one", "two"])]


arrays
s1 = pd.Series(np.random.rand(8), index = arrays)
s1

[array(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
       dtype='<U3'),
 array(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'],
       dtype='<U3')]

bar  one    0.193530
     two    0.232051
baz  one    0.579079
     two    0.416695
foo  one    0.576644
     two    0.923909
qux  one    0.412889
     two    0.824854
dtype: float64

#### 예2. 키를 튜플로 갖는 딕셔너리의 데이터로 Series 생성

In [27]:
# 키를 튜플로 갖는 딕셔너리 데이터
data = {('James', 'Eng'): 100,
        ('James', 'Math') : 90,
        ('Ted', 'Eng') : 90,
        ('Ted', 'Math') : 70,
        ('Adam', 'Eng') : 85,
        ('Adam', 'Math') : 90 }
data
s2 = pd.Series(data)

{('James', 'Eng'): 100,
 ('James', 'Math'): 90,
 ('Ted', 'Eng'): 90,
 ('Ted', 'Math'): 70,
 ('Adam', 'Eng'): 85,
 ('Adam', 'Math'): 90}

In [24]:
s2.index

MultiIndex([('James',  'Eng'),
            ('James', 'Math'),
            (  'Ted',  'Eng'),
            (  'Ted', 'Math'),
            ( 'Adam',  'Eng'),
            ( 'Adam', 'Math')],
           )

#### 인덱스의 이름 지정 : 시리즈.index.names = [ , ]

In [28]:
s2.index.namesv #FrozenList([None, None])
s2.index.names = ['name','couse']
s2

FrozenList([None, None])

name   couse
James  Eng      100
       Math      90
Ted    Eng       90
       Math      70
Adam   Eng       85
       Math      90
dtype: int64

#### 다중인덱스를 갖는 Series의 인덱싱

- 시리즈[상위인덱스]
- 시리즈.상위인덱스
- 시리즈[(상위인덱스, 하위인덱스)]
- 시리즈.상위인데스.하위인덱스
- 시리즈[:, 하위인덱스]

In [33]:
s2['James']
s2.James

couse
Eng     100
Math     90
dtype: int64

couse
Eng     100
Math     90
dtype: int64

In [36]:
s2.Ted
s2['Ted','Math']

couse
Eng     90
Math    70
dtype: int64

np.int64(70)

In [35]:
s2.Ted.Math

np.int64(70)

In [37]:
s2[['James','Adam']]

name   couse
James  Eng      100
       Math      90
Adam   Eng       85
       Math      90
dtype: int64

In [40]:
s2[['James', 'Adam']]

name   couse
James  Eng      100
       Math      90
Adam   Eng       85
       Math      90
dtype: int64

In [41]:
s2[:,'Math']

name
James    90
Ted      70
Adam     90
dtype: int64

### 2. 다중 인덱스를 갖는 DataFrame

- 데이터 프레임 생성 시 생성자에서 columns인수나 index 인수를  2차원 리스트(행렬) 형태로 지정할 경우

#### 1) column인덱스를 다중 인덱스로 갖는 DataFrame

In [43]:
np.random.seed(0)
data = np.round(np.random.randn(5,4),2)
data

array([[ 1.76,  0.4 ,  0.98,  2.24],
       [ 1.87, -0.98,  0.95, -0.15],
       [-0.1 ,  0.41,  0.14,  1.45],
       [ 0.76,  0.12,  0.44,  0.33],
       [ 1.49, -0.21,  0.31, -0.85]])

In [46]:
df = pd.DataFrame(data=data,
                  columns=[['A','A','B','B'],['C1','C2','C3','C4']]
                 )

In [48]:
df
df.columns

      A           B
     C1    C2    C3    C4
0  1.76  0.40  0.98  2.24
1  1.87 -0.98  0.95 -0.15
2 -0.10  0.41  0.14  1.45
3  0.76  0.12  0.44  0.33
4  1.49 -0.21  0.31 -0.85

MultiIndex([('A', 'C1'),
            ('A', 'C2'),
            ('B', 'C3'),
            ('B', 'C4')],
           )

#### 열 인덱싱(1): df[상위인덱스]
- 상위 인덱스의 모든 열에 대한 데이터프레임 반환

In [49]:
df['A']

     C1    C2
0  1.76  0.40
1  1.87 -0.98
2 -0.10  0.41
3  0.76  0.12
4  1.49 -0.21

#### 열 인덱싱(2): df[(상위인덱스, 하위인덱스)]
- 인덱스가 하나가 아니므로 묶어서(튜플로) 전달해야 함
- 시리즈로 반환

In [50]:
df[('A','C1')]

0    1.76
1    1.87
2   -0.10
3    0.76
4    1.49
Name: (A, C1), dtype: float64

In [51]:
df['A','C1']

0    1.76
1    1.87
2   -0.10
3    0.76
4    1.49
Name: (A, C1), dtype: float64

#### 열인덱싱(3) :  . 연산자로 확장

- df.상위인덱스
- df.상위인덱스.하위인덱스

In [52]:
df.A
df.A.C1

     C1    C2
0  1.76  0.40
1  1.87 -0.98
2 -0.10  0.41
3  0.76  0.12
4  1.49 -0.21

0    1.76
1    1.87
2   -0.10
3    0.76
4    1.49
Name: C1, dtype: float64

#### 열인덱스 이름 지정 : df.columns.names = []

In [53]:
df.columns
df.columns.names
df.columns.names = ['upper','lower']
df

MultiIndex([('A', 'C1'),
            ('A', 'C2'),
            ('B', 'C3'),
            ('B', 'C4')],
           )

FrozenList([None, None])

upper     A           B
lower    C1    C2    C3    C4
0      1.76  0.40  0.98  2.24
1      1.87 -0.98  0.95 -0.15
2     -0.10  0.41  0.14  1.45
3      0.76  0.12  0.44  0.33
4      1.49 -0.21  0.31 -0.85

#### 2) 행인덱스를 다중 인덱스로 갖는 DataFrame

In [55]:
data2 = np.random.randint(1,10, size=(4,4))
data2
df2 = pd.DataFrame(data2, 
                  index=[['a','a','b','b'],
                         ['1','2','1','2']],
                  columns= ['A','B','C','D'])
df2
df2.index

array([[5, 9, 2, 2],
       [8, 4, 7, 8],
       [3, 1, 4, 6],
       [5, 5, 7, 5]], dtype=int32)

     A  B  C  D
a 1  5  9  2  2
  2  8  4  7  8
b 1  3  1  4  6
  2  5  5  7  5

MultiIndex([('a', '1'),
            ('a', '2'),
            ('b', '1'),
            ('b', '2')],
           )

#### 행인덱싱(1) : df.loc[상위인덱스]

In [56]:
df2.loc['a']
df2.loc['a':'b']

   A  B  C  D
1  5  9  2  2
2  8  4  7  8

     A  B  C  D
a 1  5  9  2  2
  2  8  4  7  8
b 1  3  1  4  6
  2  5  5  7  5

#### 행인덱싱(2) : df.loc[(상위인덱스, 하위인덱스)]
- 상위인덱스와 하위인덱스를 튜플로 전달

In [57]:
df2.loc[('a','1')]
df2.loc['a','1']

A    5
B    9
C    2
D    2
Name: (a, 1), dtype: int32

A    5
B    9
C    2
D    2
Name: (a, 1), dtype: int32

#### 인덱서 iloc : df.iloc[  ]
- iloc인덱서는 행이름, 열이름 기반이 아님

In [61]:
df2.iloc[:]
df2.iloc[:]

     A  B  C  D
a 1  5  9  2  2
  2  8  4  7  8
b 1  3  1  4  6
  2  5  5  7  5

In [62]:
df2.iloc[1,1:]

B    4
C    7
D    8
Name: (a, 2), dtype: int32

In [64]:
df2.iloc[0,0]

np.int32(5)

#### 3)  행과 열에 모두 다중인덱스를 갖는 DataFrame

In [65]:
np.random.seed(0)
data3 = np.round(np.random.randn(6,4),2)
col1 = ['A']*2 + ['B']*2
col2 = ['C'+str(i) for i in range(1,5)]
columns = [col1, col2]
columns
idx1 = ['M']*3 + ['F']*3
idx2 = ['id_'+str(i) for i in range(1,4)]*2
index = [idx1, idx2]
index

[['A', 'A', 'B', 'B'], ['C1', 'C2', 'C3', 'C4']]

[['M', 'M', 'M', 'F', 'F', 'F'],
 ['id_1', 'id_2', 'id_3', 'id_1', 'id_2', 'id_3']]

In [66]:
df3 = pd.DataFrame(data3, index=index, columns=columns)
df3

           A           B
          C1    C2    C3    C4
M id_1  1.76  0.40  0.98  2.24
  id_2  1.87 -0.98  0.95 -0.15
  id_3 -0.10  0.41  0.14  1.45
F id_1  0.76  0.12  0.44  0.33
  id_2  1.49 -0.21  0.31 -0.85
  id_3 -2.55  0.65  0.86 -0.74

#### 행/열 각 인덱스에 이름(names) 설정

- 이름을 지정하면 직관성이 높아지고 편리하게 사용할 수 있음
- 열이름/행이름 구분하는데 용이
- 문법
    - df.columns.names = 값 또는 리스트
    - df.index.names = 값 또는 리스트

In [70]:
df3.columns.names = ['Cidx1','Cidx2']
df3.index.names = ['Ridx1','Ridx2']
df3

Cidx1           A           B
Cidx2          C1    C2    C3    C4
Ridx1 Ridx2
M     id_1   1.76  0.40  0.98  2.24
      id_2   1.87 -0.98  0.95 -0.15
      id_3  -0.10  0.41  0.14  1.45
F     id_1   0.76  0.12  0.44  0.33
      id_2   1.49 -0.21  0.31 -0.85
      id_3  -2.55  0.65  0.86 -0.74

### 3. MultiIndex 객체
- https://pandas.pydata.org/docs/user_guide/advanced.html

- 생성 방법
1. MultiIndex.from_arrays() 사용 : 배열(array)의 리스트
2. MultiIndex.from_tuples() : 튜플들(tuples)의 리스트
3. MultiIndex.from_product() : 리스트의 cross product
4. MultiIndex.from_frame() : DataFrame

In [78]:
# 1. MultiIndex.from_arrays() 이용한 다중인덱스 생성
arrays = np.array([["one", "two", "one", "two"],
                   ["bar", "baz", "foo", "qux"]])
arrays
index = pd.MultiIndex.from_arrays(arrays, 
                                  names=["first", "second"])
index

array([['one', 'two', 'one', 'two'],
       ['bar', 'baz', 'foo', 'qux']], dtype='<U3')

MultiIndex([('one', 'bar'),
            ('two', 'baz'),
            ('one', 'foo'),
            ('two', 'qux')],
           names=['first', 'second'])

In [74]:
# 1. MultiIndex.from_arrays() 이용한 다중인덱스 생성
# pd.colums.MultiIndex.from_arrays()

AttributeError: module 'pandas' has no attribute 'colums'

In [77]:
# 2. MultiIndex.from_tuples() 이용한 다중인덱스 생성
arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"]]
tuples = list(zip(*arrays))
tuples
index = pd.MultiIndex.from_tuples(tuples, 
                                  names=["first", "second"])
index

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [80]:
# 3. MultiIndex.from_product() 사용한 다중인덱스 생성
iterables = [["bar", "baz", "foo", "qux"], ["one", "two"]]
pd.MultiIndex.from_product(iterables,
                           names=["first", "second"])

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [81]:
# 4. MultiIndex.from_frame()를 사용한 다중인덱스 생성
df = pd.DataFrame([["bar", "one"], ["bar", "two"],
                   ["foo", "one"], ["foo", "two"]],
                  columns=["first", "second"])
df
pd.MultiIndex.from_frame(df)

  first second
0   bar    one
1   bar    two
2   foo    one
3   foo    two

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('foo', 'one'),
            ('foo', 'two')],
           names=['first', 'second'])

In [82]:
import numpy as np
import pandas as pd

# 1. 예시 데이터프레임 생성 (from_frame 예제 코드 활용)
df = pd.DataFrame(
    [["bar", "one"], ["bar", "two"], ["foo", "one"], ["foo", "two"]],
    columns=["first", "second"],
)

# 2. pd.MultiIndex.from_frame()을 이용해 멀티인덱스 객체 생성
multi_idx = pd.MultiIndex.from_frame(df)

# 3. 생성된 멀티인덱스를 실제 DataFrame의 행 인덱스로 할당
# (4개의 행에 매칭될 임의의 값 데이터 생성)
np.random.seed(42)
data_df = pd.DataFrame(
    np.random.randn(4, 2), index=multi_idx, columns=["Value1", "Value2"]
)

data_df

                Value1    Value2
first second
bar   one     0.496714 -0.138264
      two     0.647689  1.523030
foo   one    -0.234153 -0.234137
      two     1.579213  0.767435

#### 예제. MultiIndex객체 생성하여 다중인덱스 설정

In [88]:
data4 = np.round(np.random.rand(4,9),1)
data4

index = pd.MultiIndex.from_product([[1995,2000],['May','Dec']], names=['Year','Month'])
index

columns = pd.MultiIndex.from_product([['A','B','C'],[1,2,3]], names=['name','count'])
columns

df4 = pd.DataFrame(data = data4,
                   index = index,
                   columns = columns
)
df4

array([[0.3, 0.1, 0.3, 0.3, 0.7, 0.6, 0.9, 0.5, 0.1],
       [0.7, 0.8, 0.6, 0.8, 0.5, 0.5, 0.4, 0. , 0.1],
       [0. , 0.6, 0.3, 0.5, 0.9, 0.2, 0.4, 0.8, 0.2],
       [0.1, 0.3, 0.2, 0.9, 0.8, 0.6, 0.9, 0.8, 0.2]])

MultiIndex([(1995, 'May'),
            (1995, 'Dec'),
            (2000, 'May'),
            (2000, 'Dec')],
           names=['Year', 'Month'])

MultiIndex([('A', 1),
            ('A', 2),
            ('A', 3),
            ('B', 1),
            ('B', 2),
            ('B', 3),
            ('C', 1),
            ('C', 2),
            ('C', 3)],
           names=['name', 'count'])

name          A              B              C
count         1    2    3    1    2    3    1    2    3
Year Month
1995 May    0.3  0.1  0.3  0.3  0.7  0.6  0.9  0.5  0.1
     Dec    0.7  0.8  0.6  0.8  0.5  0.5  0.4  0.0  0.1
2000 May    0.0  0.6  0.3  0.5  0.9  0.2  0.4  0.8  0.2
     Dec    0.1  0.3  0.2  0.9  0.8  0.6  0.9  0.8  0.2

In [109]:
# df4['A']
# df4.loc[1995]
# df4.loc[(, 'Dec'), :]
# df4.loc[:, ('A', 1)]
df4['A']
df4.loc['1995']
df4.loc[:, 'Dec']
df4[:, 1]

SyntaxError: invalid syntax (4009097225.py, line 3)

### 4. 다중인덱스의 특정 레벨 제거 : droplevel(level, axis)

#### 1) 시리즈의 다중인덱스 레벨 제거

In [95]:
df4
df4.reset_index()

name          A              B              C
count         1    2    3    1    2    3    1    2    3
Year Month
1995 May    0.3  0.1  0.3  0.3  0.7  0.6  0.9  0.5  0.1
     Dec    0.7  0.8  0.6  0.8  0.5  0.5  0.4  0.0  0.1
2000 May    0.0  0.6  0.3  0.5  0.9  0.2  0.4  0.8  0.2
     Dec    0.1  0.3  0.2  0.9  0.8  0.6  0.9  0.8  0.2

name   Year Month    A              B              C
count                1    2    3    1    2    3    1    2    3
0      1995   May  0.3  0.1  0.3  0.3  0.7  0.6  0.9  0.5  0.1
1      1995   Dec  0.7  0.8  0.6  0.8  0.5  0.5  0.4  0.0  0.1
2      2000   May  0.0  0.6  0.3  0.5  0.9  0.2  0.4  0.8  0.2
3      2000   Dec  0.1  0.3  0.2  0.9  0.8  0.6  0.9  0.8  0.2

#### 2) 데이터프레임에서 다중인덱스 레벨 제거

#### 행인덱스 레벨 제거

In [97]:
df4.droplevel(0)

name     A              B              C
count    1    2    3    1    2    3    1    2    3
Month
May    0.3  0.1  0.3  0.3  0.7  0.6  0.9  0.5  0.1
Dec    0.7  0.8  0.6  0.8  0.5  0.5  0.4  0.0  0.1
May    0.0  0.6  0.3  0.5  0.9  0.2  0.4  0.8  0.2
Dec    0.1  0.3  0.2  0.9  0.8  0.6  0.9  0.8  0.2

In [101]:
df4.droplevel(1)

name     A              B              C
count    1    2    3    1    2    3    1    2    3
Year
1995   0.3  0.1  0.3  0.3  0.7  0.6  0.9  0.5  0.1
1995   0.7  0.8  0.6  0.8  0.5  0.5  0.4  0.0  0.1
2000   0.0  0.6  0.3  0.5  0.9  0.2  0.4  0.8  0.2
2000   0.1  0.3  0.2  0.9  0.8  0.6  0.9  0.8  0.2

#### 열인덱스 레벨 제거

In [103]:
df4.droplevel(0, axis=1)

count         1    2    3    1    2    3    1    2    3
Year Month
1995 May    0.3  0.1  0.3  0.3  0.7  0.6  0.9  0.5  0.1
     Dec    0.7  0.8  0.6  0.8  0.5  0.5  0.4  0.0  0.1
2000 May    0.0  0.6  0.3  0.5  0.9  0.2  0.4  0.8  0.2
     Dec    0.1  0.3  0.2  0.9  0.8  0.6  0.9  0.8  0.2

In [104]:
df4.droplevel(1, axis=1)

name          A    A    A    B    B    B    C    C    C
Year Month
1995 May    0.3  0.1  0.3  0.3  0.7  0.6  0.9  0.5  0.1
     Dec    0.7  0.8  0.6  0.8  0.5  0.5  0.4  0.0  0.1
2000 May    0.0  0.6  0.3  0.5  0.9  0.2  0.4  0.8  0.2
     Dec    0.1  0.3  0.2  0.9  0.8  0.6  0.9  0.8  0.2

### 5. 행인덱스 레벨 해제 : unstack()

: 행인덱스 -> 열인덱스로 변환

#### 1) 시리즈의 다중인덱스 레벨 해제

- 해제된 레벨 인덱스는 열인덱스로 변경되며, 데이터프레임으로 반환됨
- 형식
```python
DateFrame.unstack(level=1, fill_value=None)


level : int, str, or list of these, default last level
    Level(s) to unstack, can pass level name.
fill_value : scalar value, default None
    Value to use when replacing NaN values.
sort : bool, default True
    Sort the level(s) in the resulting MultiIndex columns.
```

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.unstack.html

In [107]:
s1

bar  one    0.193530
     two    0.232051
baz  one    0.579079
     two    0.416695
foo  one    0.576644
     two    0.923909
qux  one    0.412889
     two    0.824854
dtype: float64

#### 마지막 레벨 해제 : unstack(level=-1)

In [112]:
s1.unstack()
s1.unstack(level=-1)
s1.unstack(level=1)

          one       two
bar  0.193530  0.232051
baz  0.579079  0.416695
foo  0.576644  0.923909
qux  0.412889  0.824854

          one       two
bar  0.193530  0.232051
baz  0.579079  0.416695
foo  0.576644  0.923909
qux  0.412889  0.824854

          one       two
bar  0.193530  0.232051
baz  0.579079  0.416695
foo  0.576644  0.923909
qux  0.412889  0.824854

#### 첫번째 레벨 해제 : unstack(level=0)

In [110]:
s1.unstack(level = 0)

          bar       baz       foo       qux
one  0.193530  0.579079  0.576644  0.412889
two  0.232051  0.416695  0.923909  0.824854

#### 2) 데이터프레임의 다중 행인덱스 레벨 해제

- 데이터프레임의 인덱스 레벨 해제
- 해제된 레벨은 열인덱스 중 가장 마지막 레벨이 됨

[형식]

```python
DateFrame.unstack(level=1, fill_value=None)
```

- level : int, str, or list of these, default= -1 (last level)
    - Level(s) of index to unstack, can pass level name.

- fill_value : int, str or dict
    - Replace NaN with this value if the unstack produces missing values.
- sort : 

- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html

In [114]:
df4

name          A              B              C
count         1    2    3    1    2    3    1    2    3
Year Month
1995 May    0.3  0.1  0.3  0.3  0.7  0.6  0.9  0.5  0.1
     Dec    0.7  0.8  0.6  0.8  0.5  0.5  0.4  0.0  0.1
2000 May    0.0  0.6  0.3  0.5  0.9  0.2  0.4  0.8  0.2
     Dec    0.1  0.3  0.2  0.9  0.8  0.6  0.9  0.8  0.2

In [115]:
df4.unstack(0)

name     A                             B                             C       \
count    1         2         3         1         2         3         1
Year  1995 2000 1995 2000 1995 2000 1995 2000 1995 2000 1995 2000 1995 2000
Month
Dec    0.7  0.1  0.8  0.3  0.6  0.2  0.8  0.9  0.5  0.8  0.5  0.6  0.4  0.9
May    0.3  0.0  0.1  0.6  0.3  0.3  0.3  0.5  0.7  0.9  0.6  0.2  0.9  0.4

name
count    2         3
Year  1995 2000 1995 2000
Month
Dec    0.0  0.8  0.1  0.2
May    0.5  0.8  0.1  0.2

In [118]:
# 레벨의 이름으로 지정하여 해제
df4.unstack('Month')
# df4.unstack(level='Month')

name     A                             B                             C       \
count    1         2         3         1         2         3         1
Month  Dec  May  Dec  May  Dec  May  Dec  May  Dec  May  Dec  May  Dec  May
Year
1995   0.7  0.3  0.8  0.1  0.6  0.3  0.8  0.3  0.5  0.7  0.5  0.6  0.4  0.9
2000   0.1  0.0  0.3  0.6  0.2  0.3  0.9  0.5  0.8  0.9  0.6  0.2  0.9  0.4

name
count    2         3
Month  Dec  May  Dec  May
Year
1995   0.0  0.5  0.1  0.1
2000   0.8  0.8  0.2  0.2

### 6. 열인덱스 레벨 해제 : stack()

: 열인덱스 -> 행인덱스로 변환

#### 데이터프레임에서 열인덱스 레벨 해제

- 지정한 열인덱스가 행인덱스의 마지막 레벨로 변환 추가됨
- single level 열인덱스를 갖는 경우 시리즈로 반환
- multi level 열인덱스를 갖는 경우 데이터프레임 반환

[형식] DataFrame.stack(level=- 1, dropna=True)

- level위치 또는 열이름 지정
- level : int, str, list, default= -1
- dropna : bool, default True

- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html

#### 예1. 1차 레벨을 가진 데이터프레임

In [123]:
df = pd.DataFrame(data=[[0,1],[2,3]],
                 index=['cat','dog'],
                 columns=['weight','height']
)
df

     weight  height
cat       0       1
dog       2       3

In [122]:
df.stack()

cat  weight    0
     height    1
dog  weight    2
     height    3
dtype: int64

In [124]:
df.stack(-1)

cat  weight    0
     height    1
dog  weight    2
     height    3
dtype: int64

In [125]:
df.stack(0)

cat  weight    0
     height    1
dog  weight    2
     height    3
dtype: int64

#### 예2. 다중레벨을 갖는 데이터프레임

In [127]:
df4
df4.stack()

name          A              B              C
count         1    2    3    1    2    3    1    2    3
Year Month
1995 May    0.3  0.1  0.3  0.3  0.7  0.6  0.9  0.5  0.1
     Dec    0.7  0.8  0.6  0.8  0.5  0.5  0.4  0.0  0.1
2000 May    0.0  0.6  0.3  0.5  0.9  0.2  0.4  0.8  0.2
     Dec    0.1  0.3  0.2  0.9  0.8  0.6  0.9  0.8  0.2

name                A    B    C
Year Month count
1995 May   1      0.3  0.3  0.9
           2      0.1  0.7  0.5
           3      0.3  0.6  0.1
     Dec   1      0.7  0.8  0.4
           2      0.8  0.5  0.0
           3      0.6  0.5  0.1
2000 May   1      0.0  0.5  0.4
           2      0.6  0.9  0.8
           3      0.3  0.2  0.2
     Dec   1      0.1  0.9  0.9
           2      0.3  0.8  0.8
           3      0.2  0.6  0.2

In [128]:
df4.stack().stack()

Year  Month  count  name
1995  May    1      A       0.3
                    B       0.3
                    C       0.9
             2      A       0.1
                    B       0.7
                    C       0.5
             3      A       0.3
                    B       0.6
                    C       0.1
      Dec    1      A       0.7
                    B       0.8
                    C       0.4
             2      A       0.8
                    B       0.5
                    C       0.0
             3      A       0.6
                    B       0.5
                    C       0.1
2000  May    1      A       0.0
                    B       0.5
                    C       0.4
             2      A       0.6
                    B       0.9
                    C       0.8
             3      A       0.3
                    B       0.2
                    C       0.2
      Dec    1      A       0.1
                    B       0.9
                    C       0.9
             2      A       0.3
                    B       0.8
                    C       0.8
             3      A       0.2
                    B       0.6
                    C       0.2
dtype: float64

In [131]:
df4.stack(level = 1)
df4.stack(level = 0)

name                A    B    C
Year Month count
1995 May   1      0.3  0.3  0.9
           2      0.1  0.7  0.5
           3      0.3  0.6  0.1
     Dec   1      0.7  0.8  0.4
           2      0.8  0.5  0.0
           3      0.6  0.5  0.1
2000 May   1      0.0  0.5  0.4
           2      0.6  0.9  0.8
           3      0.3  0.2  0.2
     Dec   1      0.1  0.9  0.9
           2      0.3  0.8  0.8
           3      0.2  0.6  0.2

count              1    2    3
Year Month name
1995 May   A     0.3  0.1  0.3
           B     0.3  0.7  0.6
           C     0.9  0.5  0.1
     Dec   A     0.7  0.8  0.6
           B     0.8  0.5  0.5
           C     0.4  0.0  0.1
2000 May   A     0.0  0.6  0.3
           B     0.5  0.9  0.2
           C     0.4  0.8  0.2
     Dec   A     0.1  0.3  0.2
           B     0.9  0.8  0.6
           C     0.9  0.8  0.2

In [136]:
df4.stack(level = 'name')

count              1    2    3
Year Month name
1995 May   A     0.3  0.1  0.3
           B     0.3  0.7  0.6
           C     0.9  0.5  0.1
     Dec   A     0.7  0.8  0.6
           B     0.8  0.5  0.5
           C     0.4  0.0  0.1
2000 May   A     0.0  0.6  0.3
           B     0.5  0.9  0.2
           C     0.4  0.8  0.2
     Dec   A     0.1  0.3  0.2
           B     0.9  0.8  0.6
           C     0.9  0.8  0.2

#### 예3. 열인덱스 이름을 갖는 데이터프레임

In [139]:
df4.unstack()

name     A                             B                             C       \
count    1         2         3         1         2         3         1
Month  Dec  May  Dec  May  Dec  May  Dec  May  Dec  May  Dec  May  Dec  May
Year
1995   0.7  0.3  0.8  0.1  0.6  0.3  0.8  0.3  0.5  0.7  0.5  0.6  0.4  0.9
2000   0.1  0.0  0.3  0.6  0.2  0.3  0.9  0.5  0.8  0.9  0.6  0.2  0.9  0.4

name
count    2         3
Month  Dec  May  Dec  May
Year
1995   0.0  0.5  0.1  0.1
2000   0.8  0.8  0.2  0.2

### 7. 다중인덱스의 레벨 교환 : swaplevel()

[형식] DataFrame.swaplevel(i=- 2, j=- 1, axis=0)

- i, j : int or str
    - Levels of the indices to be swapped. Can pass level name as string.

- axis : 0 or ‘index’, 1 or ‘columns', default=0
    - The axis to swap levels on
    - 0 or‘index’ for row-wise
    - 1 or ‘columns’ for column-wise

- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.swaplevel.html

In [137]:
df = pd.DataFrame({"Grade": ["A", "B", "A", "C"]},
                  index=[
                      ["Final exam", "Final exam", "Coursework", "Coursework"],
                      ["History", "Geography", "History", "Geography"],
                      ["January", "February", "March", "April"],],)
df

                              Grade
Final exam History   January      A
           Geography February     B
Coursework History   March        A
           Geography April        C

In [143]:
df
df.swaplevel()
# df.swaplevel(axis = 1) # TypeError: Can only swap levels on a hierarchical axis.
# 다중인덱스에서만 사용 가능
df.swaplevel(0,1)

                              Grade
Final exam History   January      A
           Geography February     B
Coursework History   March        A
           Geography April        C

                              Grade
Final exam January  History       A
           February Geography     B
Coursework March    History       A
           April    Geography     C

                              Grade
History   Final exam January      A
Geography Final exam February     B
History   Coursework March        A
Geography Coursework April        C

### [정리] 다중인덱스의 접근 방법

- 인덱스가 하나가 아니므로 묶어서(튜플로) 전달
- 열 접근 : df[(튜플)]
- 행 접근 : df.loc[(튜플)]
- 참고. df.iloc[]은 정수위치로 접근하여 다중인덱스에 구애받지 않음

-----

### 8. 다중인덱스의 행/열 추가

In [147]:
data = np.round(np.random.rand(6, 4), 2)
columns = pd.MultiIndex.from_product([['A','B'],['C1','C2']],
                                   names=['cidx1','cidx2'])
index = pd.MultiIndex.from_product([['M','F'],['id1','id2','id3']],
                                    names=['ridx1','ridx2'])
df2 = pd.DataFrame(data=data, index=index, columns=columns)
df2

cidx1           A           B
cidx2          C1    C2    C1    C2
ridx1 ridx2
M     id1    0.32  0.19  0.04  0.59
      id2    0.68  0.02  0.51  0.23
      id3    0.65  0.17  0.69  0.39
F     id1    0.94  0.14  0.34  0.11
      id2    0.92  0.88  0.26  0.66
      id3    0.82  0.56  0.53  0.24

#### 값입력을 위한 위치 지정 실수?

In [149]:
df2.loc[('F','id1'),('B','C1')]

np.float64(0.34)

In [150]:
df2.loc[('F','id1'),('B','c1')] = 100

In [152]:
df2

cidx1           A           B
cidx2          C1    C2    C1    C2     c1
ridx1 ridx2
M     id1    0.32  0.19  0.04  0.59    NaN
      id2    0.68  0.02  0.51  0.23    NaN
      id3    0.65  0.17  0.69  0.39    NaN
F     id1    0.94  0.14  0.34  0.11  100.0
      id2    0.92  0.88  0.26  0.66    NaN
      id3    0.82  0.56  0.53  0.24    NaN

In [155]:
df2 = df2.drop(columns=('B','c1'))
df2

cidx1           A           B
cidx2          C1    C2    C1    C2
ridx1 ridx2
M     id1    0.32  0.19  0.04  0.59
      id2    0.68  0.02  0.51  0.23
      id3    0.65  0.17  0.69  0.39
F     id1    0.94  0.14  0.34  0.11
      id2    0.92  0.88  0.26  0.66
      id3    0.82  0.56  0.53  0.24

#### 각 행의 총합을 마지막 열로 추가

In [161]:
df2[('Row','Sum')]=df2.sum(axis=1)

In [162]:
#df2['sum'] = df2.sum(axis=1)
# df2
# df2 = df2.drop(columns='sum')
df2

cidx1           A           B         Row
cidx2          C1    C2    C1    C2   Sum
ridx1 ridx2
M     id1    0.32  0.19  0.04  0.59  1.14
      id2    0.68  0.02  0.51  0.23  1.44
      id3    0.65  0.17  0.69  0.39  1.90
F     id1    0.94  0.14  0.34  0.11  1.53
      id2    0.92  0.88  0.26  0.66  2.72
      id3    0.82  0.56  0.53  0.24  2.15

In [167]:
df2.drop(('M','id3'))
df2.drop(('A','C2'), axis=1)

cidx1           A           B          Row
cidx2          C1    C2    C1    C2    Sum
ridx1 ridx2
M     id1    0.32  0.19  0.04  0.59   1.14
      id2    0.68  0.02  0.51  0.23   1.44
F     id1    0.94  0.14  0.34  0.11   1.53
      id2    0.92  0.88  0.26  0.66   2.72
      id3    0.82  0.56  0.53  0.24   2.15
Col   Sum    4.33  1.96  2.37  2.22  10.88

cidx1           A     B          Row
cidx2          C1    C1    C2    Sum
ridx1 ridx2
M     id1    0.32  0.04  0.59   1.14
      id2    0.68  0.51  0.23   1.44
      id3    0.65  0.69  0.39   1.90
F     id1    0.94  0.34  0.11   1.53
      id2    0.92  0.26  0.66   2.72
      id3    0.82  0.53  0.24   2.15
Col   Sum    4.33  2.37  2.22  10.88

#### 각 열의 총합을 마지막 행으로 추가

In [163]:
df2.loc[('Col', 'Sum'),:] = df2.sum(axis=0)
df2

cidx1           A           B          Row
cidx2          C1    C2    C1    C2    Sum
ridx1 ridx2
M     id1    0.32  0.19  0.04  0.59   1.14
      id2    0.68  0.02  0.51  0.23   1.44
      id3    0.65  0.17  0.69  0.39   1.90
F     id1    0.94  0.14  0.34  0.11   1.53
      id2    0.92  0.88  0.26  0.66   2.72
      id3    0.82  0.56  0.53  0.24   2.15
Col   Sum    4.33  1.96  2.37  2.22  10.88

### 9. 다중인덱스 정렬

### 1) sort_index()

[형식] sort_index(*, axis=0, level=None, ascending=True, inplace=False,)

- 행/열 인덱스 기준으로 정렬
- 기본 정렬 방식 : 오름차순 정렬
- 내림차순 : ascending=Flase 설정

####  행인덱스 정렬

In [168]:
df

cidx1           A           B
cidx2          C1    C2    C1    C2
ridx1 ridx2
M     id1    0.89  0.54  0.81  0.90
      id2    0.32  0.11  0.23  0.43
      id3    0.82  0.86  0.01  0.51
F     id1    0.42  0.22  0.12  0.34
      id2    0.94  0.32  0.52  0.70
      id3    0.36  0.97  0.96  0.25

In [170]:
df.sort_index(level=0)
df.sort_index(level=1)
df.sort_index(level=0, ascending = False)

cidx1           A           B
cidx2          C1    C2    C1    C2
ridx1 ridx2
F     id1    0.42  0.22  0.12  0.34
      id2    0.94  0.32  0.52  0.70
      id3    0.36  0.97  0.96  0.25
M     id1    0.89  0.54  0.81  0.90
      id2    0.32  0.11  0.23  0.43
      id3    0.82  0.86  0.01  0.51

cidx1           A           B
cidx2          C1    C2    C1    C2
ridx1 ridx2
F     id1    0.42  0.22  0.12  0.34
M     id1    0.89  0.54  0.81  0.90
F     id2    0.94  0.32  0.52  0.70
M     id2    0.32  0.11  0.23  0.43
F     id3    0.36  0.97  0.96  0.25
M     id3    0.82  0.86  0.01  0.51

cidx1           A           B
cidx2          C1    C2    C1    C2
ridx1 ridx2
M     id3    0.82  0.86  0.01  0.51
      id2    0.32  0.11  0.23  0.43
      id1    0.89  0.54  0.81  0.90
F     id3    0.36  0.97  0.96  0.25
      id2    0.94  0.32  0.52  0.70
      id1    0.42  0.22  0.12  0.34

#### 열인덱스 기준으로 정렬

In [171]:
df.sort_index(axis = 1)
df.sort_index(axis = 1, level=0)
df.sort_index(axis = 1, level=1)
df.sort_index(axis = 1, level=1, ascending=False)

cidx1           A           B
cidx2          C1    C2    C1    C2
ridx1 ridx2
M     id1    0.89  0.54  0.81  0.90
      id2    0.32  0.11  0.23  0.43
      id3    0.82  0.86  0.01  0.51
F     id1    0.42  0.22  0.12  0.34
      id2    0.94  0.32  0.52  0.70
      id3    0.36  0.97  0.96  0.25

cidx1           A           B
cidx2          C1    C2    C1    C2
ridx1 ridx2
M     id1    0.89  0.54  0.81  0.90
      id2    0.32  0.11  0.23  0.43
      id3    0.82  0.86  0.01  0.51
F     id1    0.42  0.22  0.12  0.34
      id2    0.94  0.32  0.52  0.70
      id3    0.36  0.97  0.96  0.25

cidx1           A     B     A     B
cidx2          C1    C1    C2    C2
ridx1 ridx2
M     id1    0.89  0.81  0.54  0.90
      id2    0.32  0.23  0.11  0.43
      id3    0.82  0.01  0.86  0.51
F     id1    0.42  0.12  0.22  0.34
      id2    0.94  0.52  0.32  0.70
      id3    0.36  0.96  0.97  0.25

cidx1           B     A     B     A
cidx2          C2    C2    C1    C1
ridx1 ridx2
M     id1    0.90  0.54  0.81  0.89
      id2    0.43  0.11  0.23  0.32
      id3    0.51  0.86  0.01  0.82
F     id1    0.34  0.22  0.12  0.42
      id2    0.70  0.32  0.52  0.94
      id3    0.25  0.97  0.96  0.36

### 2) sort_values()

[형식] 
```python
sort_values(by, *, axis=0, ascending=True, inplace=False, )

- 특정 컬럼 값을 기준으로 정렬
- by = 특정컬럼
```

    - 특정컬럼이 다중인덱스 일 경우 컬럼명을 **튜플**로 전달

#### df의 A.C1 컬럼을 기준으로 정렬

In [174]:
df.sort_values(by=('A','C1'))

cidx1           A           B
cidx2          C1    C2    C1    C2
ridx1 ridx2
M     id2    0.32  0.11  0.23  0.43
F     id3    0.36  0.97  0.96  0.25
      id1    0.42  0.22  0.12  0.34
M     id3    0.82  0.86  0.01  0.51
      id1    0.89  0.54  0.81  0.90
F     id2    0.94  0.32  0.52  0.70

In [178]:
# df.sort_values(by='A')
# ValueError: The column label 'A' is not unique
# For a multi-index, the label must be a tuple -> 꼭 튜플로 줘야함
# 한 열만 지정해야함 -> 두 개 이상의 컬럼을 갖는 레벨이므로 정렬 불가

-----------